### ISSUE TITLE
hidapi_switch: `GetInitialInputMode` always returns 0

### ISSUE THREAD

**Issue by SuperSamus** [libsdl-org/SDL#10182]
I noticed that #8108 wasn't actually solved, so I investigated and found out that `GetInitialInputMode` always returns 0, regardless of the actual initial state.

Because the logic when closing the controller is:
```c
    if (!ctx->m_bInputOnly) {
        /* Restore simple input mode for other applications */
        if (!ctx->m_nInitialInputMode || /* This is true */
            ctx->m_nInitialInputMode == k_eSwitchInputReportIDs_SimpleControllerState) {
            SetInputMode(ctx, k_eSwitchInputReportIDs_SimpleControllerState);
        }
    }
```
When exiting an application that uses SDL, the controller is always going to be set in the Simple state, even though I launched the application in the Full state.

Using Linux 6.9.7, with a Pro Controller connected via USB, and SDL 2.30.5.

**Comment by slouken** [comment]
The initial input mode is detected by reading a report from the controller during initialization. I assume that's not returning any data? Is this a Nintendo controller or a third party one?

**Comment by SuperSamus** [comment]
It's an official controller.

I added some more logging:
```c
static Uint8 GetInitialInputMode(SDL_DriverSwitch_Context *ctx)
{
    Uint8 input_mode = 0;

    int result;
    if (result = ReadInput(ctx) > 0) {
        input_mode = ctx->m_rgucReadBuffer[0];
    }
    printf("ReadInput result: %d\n", result);
    printf("Initial input mode: %d\n", ctx->m_rgucReadBuffer[0], ctx->m_rgucReadBuffer[0]);
    return input_mode;
}
```

And I get:
```
ReadInput result: 0
Initial input mode: 48
```

So it _does_ know that it's in full report mode...

<details>
<summary>If I then close the SDL app, then open it again</summary>
```
ReadInput result: 0
Initial input mode: 129
```
</details>

**Comment by slouken** [comment]
Interesting. The ReadInput result is 0, but there's data in the buffer. Are we getting a different report earlier, or is the ReadInput() call getting a report, but then returning 0 for some reason?

**Comment by SuperSamus** [comment]
It seems to be the former.

With this:
```c
static Uint8 GetInitialInputMode(SDL_DriverSwitch_Context *ctx)
{
    Uint8 input_mode = 0;
    int result;

    printf("Initial input mode start: %d\n", ctx->m_rgucReadBuffer[0]);
    if (result = ReadInput(ctx) > 0) {
        input_mode = ctx->m_rgucReadBuffer[0];
    }
    printf("GetInitialInputMode: ReadInput result: %d\n", result);
    printf("Initial input mode end: %d\n", ctx->m_rgucReadBuffer[0]);
    return input_mode;
}
```

I get:
```
Initial input mode start: 48
GetInitialInputMode: ReadInput result: 0
Initial input mode end: 48
```

**Comment by slouken** [comment]
Can you see where that's filled in?

**Comment by SuperSamus** [comment]
With the professional technique of putting `printf` everywhere, here are the logs:
[log.txt](https://github.com/user-attachments/files/16113621/log.txt)

**Comment by slouken** [comment]
What's the call stack for the very first ReadInput result?

**Comment by SuperSamus** [comment]
```
Thread 17 "CPU Thread" hit Breakpoint 4.2, ReadInput (ctx=ctx@entry=0x7fffa006ebc0) at /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:335
335     in /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c
(gdb) bt 20
#0  ReadInput (ctx=ctx@entry=0x7fffa006ebc0) at /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:335
#1  0x00007ffff4944f73 in ReadProprietaryReply (ctx=ctx@entry=0x7fffa006ebc0, expectedID=expectedID@entry=k_eSwitchProprietaryCommandIDs_Status)
    at /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:398
#2  0x00007ffff4945077 in WriteProprietary (ctx=ctx@entry=0x7fffa006ebc0, ucCommand=ucCommand@entry=k_eSwitchProprietaryCommandIDs_Status, pBuf=pBuf@entry=0x0, ucLen=ucLen@entry=0 '\000', 
    waitForReply=waitForReply@entry=SDL_TRUE) at /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:501
#3  0x00007ffff4947c1a in ReadJoyConControllerType (device=0x7fffa0088c90) at /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:1068
#4  0x00007ffff4947ccf in HIDAPI_DriverJoyCons_IsSupportedDevice (device=<optimized out>, name=<optimized out>, type=<optimized out>, vendor_id=<optimized out>, product_id=<optimized out>, 
    version=<optimized out>, interface_number=0, interface_class=0, interface_subclass=0, interface_protocol=0) at /build/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:1216
#5  0x00007ffff494d07b in HIDAPI_GetDeviceDriver (device=device@entry=0x7fffa0088c90) at /build/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:351
#6  0x00007ffff494d8d1 in HIDAPI_SetupDeviceDriver (device=device@entry=0x7fffa0088c90, removed=removed@entry=0x7fffc3dff4d4) at /build/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:525
#7  0x00007ffff494dc41 in HIDAPI_AddDevice (info=info@entry=0x7fffa00871c0, num_children=num_children@entry=0, children=children@entry=0x0)
    at /build/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:951
#8  0x00007ffff494e036 in HIDAPI_UpdateDeviceList () at /build/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:1117
#9  0x00007ffff494e562 in HIDAPI_JoystickInit () at /build/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:617
#10 0x00007ffff48757d0 in SDL_JoystickInit () at /build/SDL/src/joystick/SDL_joystick.c:645
#11 0x00007ffff4846189 in SDL_InitSubSystem_REAL (flags=12800) at /build/SDL/src/SDL.c:300
#12 0x00007ffff485d586 in SDL_InitSubSystem (a=<optimized out>) at /build/SDL/src/dynapi/SDL_dynapi_procs.h:89
```

**Comment by slouken** [comment]
Can you try this patch?
```patch
diff --git a/src/joystick/hidapi/SDL_hidapi_switch.c b/src/joystick/hidapi/SDL_hidapi_switch.c
index 8eacba632..ebf4f3c86 100644
--- a/src/joystick/hidapi/SDL_hidapi_switch.c
+++ b/src/joystick/hidapi/SDL_hidapi_switch.c
@@ -337,12 +337,28 @@ typedef struct

 static int ReadInput(SDL_DriverSwitch_Context *ctx)
 {
+    int result;
+
     /* Make sure we don't try to read at the same time a write is happening */
     if (SDL_AtomicGet(&ctx->device->rumble_pending) > 0) {
         return 0;
     }

-    return SDL_hid_read_timeout(ctx->device->dev, ctx->m_rgucReadBuffer, sizeof(ctx->m_rgucReadBuffer), 0);
+    result = SDL_hid_read_timeout(ctx->device->dev, ctx->m_rgucReadBuffer, sizeof(ctx->m_rgucReadBuffer), 0);
+
+    /* See if we can guess the initial input mode */
+    if (result > 0 && !ctx->m_bInputOnly && !ctx->m_nInitialInputMode) {
+        switch (ctx->m_rgucReadBuffer[0]) {
+        case k_eSwitchInputReportIDs_FullControllerState:
+        case k_eSwitchInputReportIDs_FullControllerAndMcuState:
+        case k_eSwitchInputReportIDs_SimpleControllerState:
+            ctx->m_nInitialInputMode = ctx->m_rgucReadBuffer[0];
+            break;
+        default:
+            break;
+        }
+    }
+    return result;
 }

 static int WriteOutput(SDL_DriverSwitch_Context *ctx, const Uint8 *data, int size)
@@ -738,14 +754,12 @@ static void SDLCALL SDL_PlayerLEDHintChanged(void *userdata, const char *name, c
     }
 }

-static Uint8 GetInitialInputMode(SDL_DriverSwitch_Context *ctx)
+static void GetInitialInputMode(SDL_DriverSwitch_Context *ctx)
 {
-    Uint8 input_mode = 0;
-
-    if (ReadInput(ctx) > 0) {
-        input_mode = ctx->m_rgucReadBuffer[0];
+    if (!ctx->m_nInitialInputMode) {
+        /* This will set the initial input mode if it can */
+        ReadInput(ctx);
     }
-    return input_mode;
 }

 static Uint8 GetDefaultInputMode(SDL_DriverSwitch_Context *ctx)
@@ -1391,7 +1405,7 @@ static SDL_bool HIDAPI_DriverSwitch_OpenJoystick(SDL_HIDAPI_Device *device, SDL_
     ctx->m_bSyncWrite = SDL_TRUE;

     if (!ctx->m_bInputOnly) {
-        ctx->m_nInitialInputMode = GetInitialInputMode(ctx);
+        GetInitialInputMode(ctx);
         ctx->m_nCurrentInputMode = ctx->m_nInitialInputMode;

         /* Initialize rumble data */

```

**Comment by SuperSamus** [comment]
With the patch, #8108 is now actually solved.
