### ISSUE TITLE
Address sanitizer reports memory leak on Linux with SDL_WINDOW_OPENGL

### ISSUE THREAD

**Issue by bjadamson** [libsdl-org/SDL#10322]
From what I could understand, you don't need to compile libc to use address sanitizer so I *believe* this following is a valid (possible) memory leak. Please let me know if this is invalid.

```C++
#include <external/sdl_full.hpp>

#define YES_LEAK

int
main(int, char**)
{
  ::SDL_Init(SDL_INIT_VIDEO);

#if defined(YES_LEAK)
  // This does report memory leaks
  SDL_Window* test = ::SDL_CreateWindow(nullptr, 100, 100, SDL_WINDOW_OPENGL);
  ::SDL_DestroyWindow(test);
#else
  // This doesn't report any memory leaks
  SDL_Window* test = ::SDL_CreateWindow(nullptr, 100, 100, 0);
  ::SDL_DestroyWindow(test);
#endif
  SDL_Quit();
}
```

Output from address sanitizer:

```bash
=================================================================
==524607==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2688 byte(s) in 1 object(s) allocated from:
    #0 0x560f24f4cb39 in calloc /home/benjaminadamson/projects/rrogue/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:75:3
    #1 0x7ffb013c55ce  (<unknown module>)
    #2 0x7ffb013c5a4c  (<unknown module>)
    #3 0x7ffb0206ff6c  (<unknown module>)
    #4 0x560f254eddfd in SDL_EGL_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_egl.c:555:40
    #5 0x560f25504df5 in X11_GLES_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/x11/SDL_x11opengles.c:55:12
    #6 0x560f250ee12b in SDL_GL_LoadLibrary_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:4136:18
    #7 0x560f250ece28 in SDL_CreateWindowWithProperties_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2311:13
    #8 0x560f250ef9b5 in SDL_CreateWindow_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2429:14
    #9 0x560f24f8fefc in SDL_CreateWindow /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/dynapi/SDL_dynapi_procs.h:135:1
    #10 0x560f24f8f04d in main /home/benjaminadamson/projects/rrogue/source/platform/sdl/main.cxx:11:22
    #11 0x7ffb01c39087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #12 0x7ffb01c3914a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14a) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #13 0x560f24eada84 in _start (/home/benjaminadamson/projects/rrogue/build-system/Debug/bin/rogue+0xa3a84)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x560f24f4cd5c in realloc /home/benjaminadamson/projects/rrogue/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:82:3
    #1 0x7ffaee486c3b  (<unknown module>)
    #2 0x7ffaee48723e  (<unknown module>)
    #3 0x7ffb01cab88a in __pthread_once_slow.isra.0 (/lib64/libc.so.6+0x9c88a) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #4 0x7ffb01cab8f8 in __pthread_once@GLIBC_2.2.5 (/lib64/libc.so.6+0x9c8f8) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #5 0x7ffaeec88cd6  (<unknown module>)
    #6 0x7ffaeed40ea9  (<unknown module>)
    #7 0x7ffaeec89014  (<unknown module>)
    #8 0x7ffaee433b61  (<unknown module>)
    #9 0x7ffaeeb204ad  (<unknown module>)
    #10 0x7ffaee435fa6  (<unknown module>)
    #11 0x7ffaee43ec2b  (<unknown module>)
    #12 0x7ffb013cb530  (<unknown module>)
    #13 0x7ffb013cfe83  (<unknown module>)
    #14 0x7ffb013cbf07  (<unknown module>)
    #15 0x7ffb013ba777  (<unknown module>)
    #16 0x560f254ee07d in SDL_EGL_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_egl.c:563:9
    #17 0x560f25504df5 in X11_GLES_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/x11/SDL_x11opengles.c:55:12
    #18 0x560f250ee12b in SDL_GL_LoadLibrary_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:4136:18
    #19 0x560f250ece28 in SDL_CreateWindowWithProperties_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2311:13
    #20 0x560f250ef9b5 in SDL_CreateWindow_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2429:14
    #21 0x560f24f8fefc in SDL_CreateWindow /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/dynapi/SDL_dynapi_procs.h:135:1
    #22 0x560f24f8f04d in main /home/benjaminadamson/projects/rrogue/source/platform/sdl/main.cxx:11:22
    #23 0x7ffb01c39087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #24 0x7ffb01c3914a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14a) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #25 0x560f24eada84 in _start (/home/benjaminadamson/projects/rrogue/build-system/Debug/bin/rogue+0xa3a84)

Indirect leak of 288 byte(s) in 2 object(s) allocated from:
    #0 0x560f24f4cb39 in calloc /home/benjaminadamson/projects/rrogue/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:75:3
    #1 0x7ffb013212d6  (<unknown module>)
    #2 0x7ffb01321653  (<unknown module>)
    #3 0x7ffb01325f9f  (<unknown module>)
    #4 0x7ffb013c500a  (<unknown module>)
    #5 0x7ffb013ba677  (<unknown module>)
    #6 0x560f254ee07d in SDL_EGL_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_egl.c:563:9
    #7 0x560f25504df5 in X11_GLES_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/x11/SDL_x11opengles.c:55:12
    #8 0x560f250ee12b in SDL_GL_LoadLibrary_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:4136:18
    #9 0x560f250ece28 in SDL_CreateWindowWithProperties_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2311:13
    #10 0x560f250ef9b5 in SDL_CreateWindow_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2429:14
    #11 0x560f24f8fefc in SDL_CreateWindow /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/dynapi/SDL_dynapi_procs.h:135:1
    #12 0x560f24f8f04d in main /home/benjaminadamson/projects/rrogue/source/platform/sdl/main.cxx:11:22
    #13 0x7ffb01c39087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #14 0x7ffb01c3914a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14a) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #15 0x560f24eada84 in _start (/home/benjaminadamson/projects/rrogue/build-system/Debug/bin/rogue+0xa3a84)

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x560f24f4cb39 in calloc /home/benjaminadamson/projects/rrogue/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:75:3
    #1 0x7ffb013c507d  (<unknown module>)
    #2 0x7ffb013ba677  (<unknown module>)
    #3 0x560f254ee07d in SDL_EGL_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_egl.c:563:9
    #4 0x560f25504df5 in X11_GLES_LoadLibrary /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/x11/SDL_x11opengles.c:55:12
    #5 0x560f250ee12b in SDL_GL_LoadLibrary_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:4136:18
    #6 0x560f250ece28 in SDL_CreateWindowWithProperties_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2311:13
    #7 0x560f250ef9b5 in SDL_CreateWindow_REAL /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/video/SDL_video.c:2429:14
    #8 0x560f24f8fefc in SDL_CreateWindow /home/benjaminadamson/projects/rrogue/source/external/SDL3/src/dynapi/SDL_dynapi_procs.h:135:1
    #9 0x560f24f8f04d in main /home/benjaminadamson/projects/rrogue/source/platform/sdl/main.cxx:11:22
    #10 0x7ffb01c39087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #11 0x7ffb01c3914a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14a) (BuildId: 8f53abaad945a669f2bdcd25f471d80e077568ef)
    #12 0x560f24eada84 in _start (/home/benjaminadamson/projects/rrogue/build-system/Debug/bin/rogue+0xa3a84)

SUMMARY: AddressSanitizer: 3312 byte(s) leaked in 6 allocation(s)
```

**Comment by slouken** [comment]
There are known leaks in third party X11 and OpenGL libraries.

**Comment by bjadamson** [comment]
For future reference, this is sufficient to quiet leak sanitizer:

file: sanitizer/lsan.supp 
```bash
leak:SDL_EGL_LoadLibrary
```
