### ISSUE TITLE
SDL_OpenAudioDeviceStream causes error with emscripten

### ISSUE THREAD

**Issue by viglietta** [libsdl-org/SDL#11258]
I compile the code below with emscripten 3.1.68, using the command line
emcc main.c -o index.html -I C:/path/to/SDL3-webassembly/include -L C:/path/to/SDL3-webassembly/lib -lSDL3 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=1gb -s EXIT_RUNTIME=1 -s ASYNCIFY=1

```c
#include <SDL3/SDL.h>
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

static void MainLoop(void){
    static SDL_Window *window;
    static SDL_AudioSpec spec;
    static Uint8 *data;
    static Uint32 length;
    static SDL_AudioStream *stream;
    static int first=1;
    if(first){
        first=0;
        SDL_Init(SDL_INIT_AUDIO|SDL_INIT_VIDEO|SDL_INIT_EVENTS);
        window=SDL_CreateWindow("Audio test",800,600,0);
        const char filename[]="0.wav";
        #ifdef __EMSCRIPTEN__
        if(emscripten_wget(filename,filename))emscripten_force_exit(1);
        #endif
        SDL_LoadWAV(filename,&spec,&data,&length);
        stream=SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK,&spec,NULL,NULL);
        SDL_ResumeAudioStreamDevice(stream);
    }
    SDL_Event e;
    while(SDL_PollEvent(&e))
        if(e.type==SDL_EVENT_QUIT){
            SDL_DestroyAudioStream(stream);
            SDL_free(data);
            SDL_DestroyWindow(window);
            SDL_Quit();
            #ifdef __EMSCRIPTEN__
            emscripten_force_exit(0);
            #else
            exit(0);
            #endif
        }
        else if(e.type==SDL_EVENT_FINGER_DOWN){
            const int minimum=(length/SDL_AUDIO_FRAMESIZE(spec))/2;
            if(SDL_GetAudioStreamQueued(stream)<minimum)SDL_PutAudioStreamData(stream,data,length);
        }
        else if(e.type==SDL_EVENT_MOUSE_BUTTON_DOWN){
            const int minimum=(length/SDL_AUDIO_FRAMESIZE(spec))/2;
            if(SDL_GetAudioStreamQueued(stream)<minimum)SDL_PutAudioStreamData(stream,data,length);
        }
}

int main(int argc,char **argv){
    (void)argc; (void)argv;
    #ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(MainLoop,0,1);
    #else
    while(1)MainLoop();
    #endif
    return 0;
}
```

When I run it in any browser, SDL_OpenAudioDeviceStream causes this warning and error, and no audio is played:

[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)

index.wasm:0x1a79e1 Uncaught RuntimeError: null function or function signature mismatch
    at index.wasm:0x1a79e1
    at ret.<computed> (index.js:9631:24)
    at index.js:619:12
    at dynCallLegacy (index.js:9530:14)
    at dynCall (index.js:9547:17)
    at SDL3.audio_playback.scriptProcessorNode.onaudioprocess (index.js:921:569)

I tried calling SDL_OpenAudioDeviceStream with a non-NULL callback, and the same error is triggered, although in a different location.

**Comment by viglietta** [comment]
As pointed out by @icculus, there is a workaround. Remove "-s ASYNCIFY=1" from the command line and download the file asynchronously with emscripten_async_wget (unless you want to embed it with --embed-file or preload it with --preload-file).

The code below works as a temporary solution, although it still trigger the same warning, "[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead."

```c
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif
#include <SDL3/SDL.h>

static const char filename[]="0.wav";
static SDL_Window *window;
static SDL_AudioSpec spec;
static Uint8 *data;
static Uint32 length;
static SDL_AudioStream *stream;
static int first=1;
static int ready=0;

#ifdef __EMSCRIPTEN__
static void SuccessCallback(const char *filename){
    ready=1;
}

static void FailCallback(const char *filename){
    emscripten_force_exit(1);
}
#endif

static void MainLoop(void){
    if(first){
        first=0;
        SDL_Init(SDL_INIT_AUDIO|SDL_INIT_VIDEO|SDL_INIT_EVENTS);
        window=SDL_CreateWindow("Audio test",800,600,0);
        #ifdef __EMSCRIPTEN__
        emscripten_async_wget(filename,filename,SuccessCallback,FailCallback);
        #else
        ready=1;
        #endif
    }
    SDL_Event e;
    while(SDL_PollEvent(&e))
        if(e.type==SDL_EVENT_QUIT){
            if(ready){
                SDL_DestroyAudioStream(stream);
                SDL_free(data);
            }
            SDL_DestroyWindow(window);
            SDL_Quit();
            #ifdef __EMSCRIPTEN__
            emscripten_force_exit(0);
            #else
            exit(0);
            #endif
        }
        else if(e.type==SDL_EVENT_FINGER_DOWN || e.type==SDL_EVENT_MOUSE_BUTTON_DOWN){
            if(ready){
                if(ready==1){
                    SDL_LoadWAV(filename,&spec,&data,&length);
                    stream=SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK,&spec,NULL,NULL);
                    SDL_ResumeAudioStreamDevice(stream);
                    ready=2;
                }
                const int minimum=(length/SDL_AUDIO_FRAMESIZE(spec))/2;
                if(SDL_GetAudioStreamQueued(stream)<minimum)SDL_PutAudioStreamData(stream,data,length);
            }
        }
}

int main(int argc,char **argv){
    (void)argc; (void)argv;
    #ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(MainLoop,0,1);
    #else
    while(1)MainLoop();
    #endif
    return 0;
}
```

**Comment by icculus** [comment]
On Firefox, the specific error is:

```
RuntimeError: indirect call signature mismatch
```

Call stack:

![image](https://github.com/user-attachments/assets/9f950691-52f5-403a-84b9-a254f14709e2)

**Comment by icculus** [comment]
> [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)

This is unrelated, fwiw (and also bad advice from the browser developers, imho).

**Comment by icculus** [comment]
Hmm, I thought maybe making the function that dynCall() calls into needed to be marked as EMSCRIPTEN_KEEPALIVE, but that didn't make a difference. @Daft-Freak, any idea why ASYNCIFY breaks this?

**Comment by Daft-Freak** [comment]
Hmm, not very familiar with ASYNCIFY. (Though I do remember it working)

Quickly looking at the code, `SDL_PlaybackAudioThreadIterate` returns a bool, so the dynCall signature (vi) is in fact wrong?

**Comment by icculus** [comment]
Oh, hah, I was too focused on the parameters and not the return value. Good catch!

Fixing the signatures definitely fixes builds with Asyncify enabled.
