### ISSUE TITLE
Memory leak in SDL3

### ISSUE THREAD

**Issue by pppppptttttt** [libsdl-org/SDL#11648]
Cloned recent version of SDL3. Buit on arch linux with Xorg server and enabled sanitizers. Minimal example:

CMakeLists.txt:
```CMake
cmake_minimum_required(VERSION 3.31)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
project(leak)

set(SDL_SHARED OFF)
set(SDL_STATIC ON)
set(SDL_TEST_LIBRARY OFF)
add_subdirectory(SDL)

add_compile_options(-fsanitize=address,undefined)
add_link_options(-fsanitize=address,undefined)

add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3-static)
```

main.cpp (surprisingly small):
```cpp
#include "SDL3/SDL.h"

int main() {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Quit();
}
```

Fragment of address sanitizer output:
```
. . .
Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7a1a14efd891 in malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7a1a11e0d6ca  (<unknown module>)
    #2 0x7a1a11e1216c  (<unknown module>)
    #3 0x5cd028879175 in X11_InitKeyboard (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x172175) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #4 0x5cd02887f77e in X11_VideoInit (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x17877e) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #5 0x5cd0287e2d5e in SDL_VideoInit (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0xdbd5e) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #6 0x5cd0288db23a in SDL_InitSubSystem_REAL (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x1d423a) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #7 0x5cd0288db4fc in SDL_Init_REAL (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x1d44fc) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #8 0x5cd028733bdb in SDL_Init_DEFAULT (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x2cbdb) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #9 0x5cd0287404a9 in SDL_Init (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x394a9) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #10 0x5cd02872e036 in main (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x27036) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)
    #11 0x7a1a14034e07  (/usr/lib/libc.so.6+0x25e07) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #12 0x7a1a14034ecb in __libc_start_main (/usr/lib/libc.so.6+0x25ecb) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #13 0x5cd02872df54 in _start (/home/pppptttt/Desktop/dev/sdl-leak/sdl-leak+0x26f54) (BuildId: eac6943829d54a17744cacdc60d363a461f31af4)

SUMMARY: AddressSanitizer: 53912 byte(s) leaked in 946 allocation(s).
```

Full log
[log.txt](https://github.com/user-attachments/files/18137911/log.txt)

**Comment by icculus** [comment]
Xlib (and the IME modules) tend to leak a little memory; it isn't an SDL bug, as far as we can tell.
