### ISSUE TITLE
Crash during HID enumeration

### ISSUE THREAD

**Issue by lat9nq** [libsdl-org/SDL#4434]
Caused by 17d8479d980ebd37707c03e4d9e86aa0438f0ab9

Rather messy, but related issue: yuzu-emu/yuzu#6343 (the issue's title is a lie, this happens on a variety of Linux distros.)

yuzu recently upgraded its SDL version to at the time the most recent commit to this repo, and later required HIDAPI support for motion input. Some Linux systems didn't agree with the changes, however, and crash during the emulator's startup.

Delay in making this issue is because I was unable to reproduce it locally and find the offending commit until very recently.

Backtrace (SDL checked out to the mentioned commit):
```
#0  0x00007ffff41dde95 in __wcslen_avx2 () at /usr/lib/libc.so.6
#1  0x00007ffff7604b3c in __interceptor_wcsdup(wchar_t*) (s=0x0) at /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:6970
#2  0x0000555558e68374 in LIBUSB_hid_enumerate (vendor_id=vendor_id@entry=0, product_id=product_id@entry=0) at yuzu/externals/SDL/src/hidapi/libusb/hid.c:735
#3  0x0000555558e69242 in hid_enumerate (vendor_id=vendor_id@entry=0, product_id=product_id@entry=0) at yuzu/externals/SDL/src/hidapi/SDL_hidapi.c:676
#4  0x0000555558e5d789 in HIDAPI_UpdateDeviceList () at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:1051
#5  0x0000555558e5f005 in HIDAPI_JoystickDetect () at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:1170
#6  HIDAPI_JoystickDetect () at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:1164
#7  HIDAPI_JoystickInit () at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:789
#8  0x0000555558e080f7 in SDL_JoystickInit () at yuzu/externals/SDL/src/joystick/SDL_joystick.c:247
#9  0x0000555558e76845 in SDL_InitSubSystem_REAL (flags=16896) at yuzu/externals/SDL/src/SDL.c:251
#10 0x000055555708a6fb in InputCommon::SDL::SDLState::SDLState() (this=this@entry=0x61200004a140) at yuzu/src/input_common/sdl/sdl_impl.cpp:837
#11 0x0000555556ffc990 in std::make_unique<InputCommon::SDL::SDLState>() () at /usr/include/c++/11.1.0/bits/unique_ptr.h:962
#12 InputCommon::SDL::Init() () at yuzu/src/input_common/sdl/sdl.cpp:14
#13 0x0000555556faeef4 in InputCommon::InputSubsystem::Impl::Initialize() (this=<optimized out>) at yuzu/src/input_common/main.cpp:45
#14 0x0000555556f93988 in InputCommon::InputSubsystem::Initialize() (this=<optimized out>) at yuzu/src/input_common/main.cpp:187
#15 0x0000555555d4bd52 in GRenderWindow::GRenderWindow(GMainWindow*, EmuThread*, std::shared_ptr<InputCommon::InputSubsystem>) (this=this@entry=
    0x614000040640, parent=parent@entry=0x7fffffffe090, emu_thread_=emu_thread_@entry=0x0, input_subsystem_=std::shared_ptr<InputCommon::InputSubsystem> (empty) = {...}) at yuzu/src/yuzu/bootmanager.cpp:296
#16 0x00005555560cc48a in GMainWindow::InitializeWidgets() (this=0x7fffffffe090) at yuzu/src/yuzu/main.cpp:710
#17 0x00005555560fe241 in GMainWindow::GMainWindow() (this=<optimized out>) at yuzu/src/yuzu/main.cpp:223
#18 0x0000555555c029dd in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at yuzu/src/yuzu/main.cpp:3376
```

**Comment by slouken** [comment]
This should be fixed by https://github.com/libsdl-org/SDL/commit/cb5e86353b97a391d865ad12974b637242289f27
