### ISSUE TITLE
Android: Apps crashing on WSA (Windows Subsystem for Android)  releated HIDDeviceManager.java

### ISSUE THREAD

**Issue by yunus-ceyhan** [libsdl-org/SDL#5133]
Almost every recently builded Kivy apps are crashing at start up on WSA. Forgive my ignorance but WSA pobably has no USB support so USB manager is not able to return USB devices list. Can anything be done about it?

```FATAL EXCEPTION: main
Process: com.ceyhan.sets, PID: 9951
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.HashMap android.hardware.usb.UsbManager.getDeviceList()' on a null object reference
	at org.libsdl.app.HIDDeviceManager.initializeUSB(HIDDeviceManager.java:227)
	at org.libsdl.app.HIDDeviceManager.<init>(HIDDeviceManager.java:152)
	at org.libsdl.app.HIDDeviceManager.acquire(HIDDeviceManager.java:35)
	at org.libsdl.app.SDLActivity.finishLoad(SDLActivity.java:264)
	at org.kivy.android.PythonActivity.access$200(PythonActivity.java:45)
	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:127)
	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:108)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by slouken** [comment]
This should be fixed, but there might be other crashes in Bluetooth and so forth. Feel free to submit new bugs for any other issues.

Thanks!
