### ISSUE TITLE
 Segmentation fault with multiple windows and renderers

### ISSUE THREAD

**Issue by arjunsatarkar** [libsdl-org/SDL#5256]
*(Originally discussed at https://discourse.libsdl.org/t/segmentation-fault-with-multiple-windows/34552)*

A simple program which creates 2 windows and a renderer for each of them is segfaulting sometimes.

Here is code that reproduces the segfault most of the time, which I have tried on two different Linux machines (one Arch, one Debian 11).
```c
#include "SDL.h"

int main(void) {
	SDL_Init(SDL_INIT_EVERYTHING);

	SDL_Window *window1 = SDL_CreateWindow("1", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 250, 250, SDL_WINDOW_RESIZABLE);
	SDL_Window *window2 = SDL_CreateWindow("2", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1000, 1000, SDL_WINDOW_RESIZABLE);

	SDL_Renderer *renderer1 = SDL_CreateRenderer(window1, -1, 0);
	SDL_Renderer *renderer2 = SDL_CreateRenderer(window2, -1, 0);

	SDL_Quit();

	return 0;
}
```

I compile this with
```
gcc -Wall -Wpedantic -O3 -o bug bug.c `sdl2-config --cflags --libs`
```
which only complains about unused variables.

Sample output of running it, when it segfaults:
```c
[aps@archlinux ~]$ ./bug
Segmentation fault (core dumped)
```

I am sometimes unable to reproduce the segfault for long stretches until it happens again.

According to user shaqeel on the forum (among other things):

> Edit: This seems to be a X11 specific problem and doesn’t happen in wayland, specifically X11_XUndefineCursor in src/video/x11/SDL_x11mouse.c:304.
> 
> I added this and it seemed to be working fine. I don’t know if it’s appropriate since I just guessed the number.
> 
> ```
> if (x11_cursor > 0) {
>     X11_XUndefineCursor(display, data->xwindow);
> }
> ```

**Comment by 1bsyl** [comment]
What happens is : 
First window is created and it triggers and 'EnterNotify' event
which calls SDL_SetMouseFocus() and X11_ShowCursor() while the second
windows hasn't finished to be created  (eg window->driverdata isn't set)
Just check for a valid 'driverdata' 

Thanks for reporting !

**Comment by 1bsyl** [comment]
more fixes...
```gdb

#0  0x00007ffff7f056f6 in X11_SetWindowMouseGrab (_this=0x420110, window=0x4665d0, grabbed=SDL_FALSE) at SDL/src/video/x11/SDL_x11window.c:1669
#1  0x00007ffff7e13767 in SDL_UpdateWindowGrab (window=0x4665d0) at SDL/src/video/SDL_video.c:2832
#2  0x00007ffff7e141c2 in SDL_OnWindowFocusLost (window=0x4665d0) at SDL/src/video/SDL_video.c:3095
#3  0x00007ffff7d1ff86 in SDL_SendWindowEvent (window=0x4665d0, windowevent=13 '\r', data1=0, data2=0) at SDL/src/events/SDL_windowevents.c:175
#4  0x00007ffff7d1b0d1 in SDL_SetKeyboardFocus (window=0x463df0) at SDL/src/events/SDL_keyboard.c:644
#5  0x00007ffff7ef376e in X11_DispatchFocusIn (_this=0x420110, data=0x463ff0) at SDL/src/video/x11/SDL_x11events.c:425
#6  0x00007ffff7ef110b in X11_DispatchEvent (_this=0x420110, xevent=0x7fffffffd5e0) at SDL/src/video/x11/SDL_x11events.c:946
#7  0x00007ffff7ef2bb8 in X11_PumpEvents (_this=0x420110) at SDL/src/video/x11/SDL_x11events.c:1682
#8  0x00007ffff7efd14c in X11_GL_InitExtensions (_this=0x420110) at SDL/src/video/x11/SDL_x11opengl.c:477
#9  0x00007ffff7efc9f5 in X11_GL_LoadLibrary (_this=0x420110, path=0x7ffff7f6882a "libGL.so.1") at SDL/src/video/x11/SDL_x11opengl.c:239
#10 0x00007ffff7e0f70c in SDL_GL_LoadLibrary_REAL (path=0x0) at SDL/src/video/SDL_video.c:3302
#11 0x00007ffff7e106b9 in SDL_RecreateWindow (window=0x4665d0, flags=518) at SDL/src/video/SDL_video.c:1902
#12 0x00007ffff7d44854 in GL_CreateRenderer (window=0x4665d0, flags=6) at SDL/src/render/opengl/SDL_render_gl.c:1717
#13 0x00007ffff7d35f2a in SDL_CreateRenderer_REAL (window=0x4665d0, index=0, flags=6) at SDL/src/render/SDL_render.c:959
#14 0x00007ffff7d01615 in SDL_CreateRenderer (a=0x4665d0, b=-1, c=6) at SDL/src/dynapi/SDL_dynapi_procs.h:332
#15 0x0000000000402568 in main (argc=1, argv=0x7fffffffdbf8) at main_diff_drawline.c:388




Thread 1 "a.out" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f056f6 in X11_SetWindowMouseGrab (_this=0x420110, window=0x468120, grabbed=SDL_FALSE) at SDL/src/video/x11/SDL_x11window.c:1669
1669	    Display *display = data->videodata->display;
(gdb) bt
#0  0x00007ffff7f056f6 in X11_SetWindowMouseGrab (_this=0x420110, window=0x468120, grabbed=SDL_FALSE) at SDL/src/video/x11/SDL_x11window.c:1669
#1  0x00007ffff7e13767 in SDL_UpdateWindowGrab (window=0x468120) at SDL/src/video/SDL_video.c:2832
#2  0x00007ffff7e141c2 in SDL_OnWindowFocusLost (window=0x468120) at SDL/src/video/SDL_video.c:3095
#3  0x00007ffff7d1ff86 in SDL_SendWindowEvent (window=0x468120, windowevent=13 '\r', data1=0, data2=0) at SDL/src/events/SDL_windowevents.c:175
#4  0x00007ffff7d1b0d1 in SDL_SetKeyboardFocus (window=0x4652e0) at SDL/src/events/SDL_keyboard.c:644
#5  0x00007ffff7ef376e in X11_DispatchFocusIn (_this=0x420110, data=0x4654c0) at SDL/src/video/x11/SDL_x11events.c:425
#6  0x00007ffff7ef110b in X11_DispatchEvent (_this=0x420110, xevent=0x7fffffffd5e0) at SDL/src/video/x11/SDL_x11events.c:946
#7  0x00007ffff7ef2bb8 in X11_PumpEvents (_this=0x420110) at SDL/src/video/x11/SDL_x11events.c:1682
#8  0x00007ffff7efd14c in X11_GL_InitExtensions (_this=0x420110) at SDL/src/video/x11/SDL_x11opengl.c:477
#9  0x00007ffff7efc9f5 in X11_GL_LoadLibrary (_this=0x420110, path=0x7ffff7f6882a "libGL.so.1") at SDL/src/video/x11/SDL_x11opengl.c:239
#10 0x00007ffff7e0f70c in SDL_GL_LoadLibrary_REAL (path=0x0) at SDL/src/video/SDL_video.c:3302
#11 0x00007ffff7e106b9 in SDL_RecreateWindow (window=0x468120, flags=518) at SDL/src/video/SDL_video.c:1902
#12 0x00007ffff7d44854 in GL_CreateRenderer (window=0x468120, flags=6) at SDL/src/render/opengl/SDL_render_gl.c:1717
#13 0x00007ffff7d35f2a in SDL_CreateRenderer_REAL (window=0x468120, index=0, flags=6) at SDL/src/render/SDL_render.c:959
#14 0x00007ffff7d01615 in SDL_CreateRenderer (a=0x468120, b=-1, c=6) at SDL/src/dynapi/SDL_dynapi_procs.h:332
#15 0x0000000000402568 in main (argc=1, argv=0x7fffffffdbf8) at main_diff_drawline.c:388
(gdb) 



```

**Comment by jacobrogers256** [comment]
Is there a workaround for older SDL2 versions? I am afflicted by this bug.

**Comment by slouken** [comment]
No, is there a reason you can't upgrade to the latest SDL version?

**Comment by jacobrogers256** [comment]
I use debian buster, and cannot update

**Comment by jacobrogers256** [comment]
I can not compile from source either

**Comment by jacobrogers256** [comment]
I use 2.0.9
