### ISSUE TITLE
Memory leak at SDL_ClearError, SDL_GetError or SDL SetError

### ISSUE THREAD

**Issue by vladimirvladimirovichnotputin** [libsdl-org/SDL#5343]
I am observing memory leak In function SDL_ClearError if it is invoked along without SDL threads functionality.
Issue is easy reproducible.
In main function just call only SDL_ClearError and then exit.
Memory leak happens inside function SDL_GetErrBuf.
88 bytes are allocated for STL storage.
132 bytes are allocated for error buffer.
But then these memory buffers are never freeing

**Comment by vladimirvladimirovichnotputin** [comment]
Indirect leak of 132 byte(s) in 1 object(s) allocated from:
    #0 0x7f12ccd1dbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f12cc907001 in SDL_malloc /sdl2/code/src/stdlib/SDL_malloc.c:5388
    #2 0x7f12cc909db2 in SDL_GetErrBuf /sdl2/code/src/thread/SDL_thread.c:247
    #3 0x7f12cc8905d9 in SDL_ClearError /sdl2/code/src/SDL_error.c:64
    #4 0x7f12cc88cfc0 in SDL_InitSubSystem /sdl2/code/src/SDL.c:159
    #5 0x7f12cc88d14d in SDL_Init /sdl2/code/src/SDL.c:308
