### ISSUE TITLE
Android: App crashes at start up on a specific device due to weird USB permission

### ISSUE THREAD

**Issue by yunus-ceyhan** [libsdl-org/SDL#5660]
The application works well on almost every device except Xiaomi Mi Pad 5, it crashes right after attempting to run the app. 

Device: Xiaomi Mi Pad 5
Android version: Android 11
Kivy: 2.1.0
Target API: 30

```05-13 08:47:55.623 11230 11230 V pythonutil: Loading library: main
05-13 08:47:55.624 11230 11230 V pythonutil: Loaded everything!
05-13 08:47:55.625 11230 11230 V SDL     : nativeSetupJNI()
05-13 08:47:55.625 11230 11230 V SDL     : AUDIO nativeSetupJNI()
05-13 08:47:55.625 11230 11230 V SDL     : CONTROLLER nativeSetupJNI()
05-13 08:47:55.628  1137  1218 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
05-13 08:47:55.629  2823 10424 D NdkImageReader: acquireImageLocked: Producer buffer usage: 333, doesn't cover all usage bits AImageReader configured: 100003
05-13 08:47:55.630  2361  2499 D HomeWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
05-13 08:47:55.633 11230 11230 D AndroidRuntime: Shutting down VM
05-13 08:47:55.634 11230 11230 E AndroidRuntime: FATAL EXCEPTION: main
05-13 08:47:55.634 11230 11230 E AndroidRuntime: Process: com.ceyhan.sets, PID: 11230
05-13 08:47:55.634 11230 11230 E AndroidRuntime: java.lang.SecurityException: User has not given 10306/com.ceyhan.sets permission to access device /dev/bus/usb/001/003
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2360)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2343)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2285)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:157)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.HIDDeviceUSB.getSerialNumber(HIDDeviceUSB.java:54)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.connectHIDDeviceUSB(HIDDeviceManager.java:368)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.handleUsbDeviceAttached(HIDDeviceManager.java:332)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.initializeUSB(HIDDeviceManager.java:228)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.<init>(HIDDeviceManager.java:152)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.acquire(HIDDeviceManager.java:35)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.libsdl.app.SDLActivity.finishLoad(SDLActivity.java:264)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.kivy.android.PythonActivity.access$100(PythonActivity.java:46)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:124)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:105)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:771)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.AsyncTask.access$900(AsyncTask.java:199)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:236)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8164)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
05-13 08:47:55.634 11230 11230 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at com.android.server.usb.UsbUserPermissionManager.checkPermission(UsbUserPermissionManager.java:654)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:98)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:84)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1160)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:1129)
05-13 08:47:55.634 11230 11230 E AndroidRuntime:
05-13 08:47:55.636  1137  3035 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
05-13 08:47:55.513  1828  1856 I chatty  : uid=1000(system) android.anim identical 1 line
05-13 08:47:55.523  1828  1856 W MiuiFreeFormGesturePointerEventListener: setMiuiFreeFormTouchExcludeRegion mTouchExcludeRegion = SkRegion((0,0,1600,60)(0,2454,1600,2560))
05-13 08:47:55.637  1828  7689 W ActivityTaskManager:   Force finishing activity com.ceyhan.sets/org.kivy.android.PythonActivity```

**Comment by MikuAuahDark** [comment]
I'm sure this was fixed in #3850. Does Kivy uses SDL 2.0.16 or later?

**Comment by markqvist** [comment]
It seems the sdl2 recipe used by the Kivy build system for android still uses SDL 2.0.9: https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/sdl2/__init__.py

**Comment by slouken** [comment]
They should upgrade and file upstream bugs if they run into any issues.
