### ISSUE TITLE
X11_Xinput2GrabTouch can call NULL X11_XIGrabTouchBegin func ptr

### ISSUE THREAD

**Issue by jengelh** [libsdl-org/SDL#5889]
I am observing a crash in a end-user program and found that, within SDL 2.0.22 i386/586/686, the `X11_XIGrabTouchBegin` function pointer is NULL, but its caller, `X11_Xinput2GrabTouch` does not check for this condition. I am not yet sure if there ought to be a check, or whether a non-NULL GrabTouchBegin is a required precondition.

```
Thread 1 "gzdoom" hit Breakpoint 1, X11_Xinput2GrabTouch (_this=0x5b63de70, window=0x5bd7c650) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/x11/SDL_x11xinput2.c:369
369         X11_XIGrabTouchBegin(display, XIAllDevices, data->xwindow, True, &eventmask, 1, &mods);
(gdb) p X11_XIGrabTouchBegin 
$4 = (SDL_DYNX11FN_XIGrabTouchBegin) 0x0
(gdb) l
364         XISetMask(eventmask.mask, XI_TouchBegin);
365         XISetMask(eventmask.mask, XI_TouchUpdate);
366         XISetMask(eventmask.mask, XI_TouchEnd);
367         XISetMask(eventmask.mask, XI_Motion);
368
369         X11_XIGrabTouchBegin(display, XIAllDevices, data->xwindow, True, &eventmask, 1, &mods);
370     #endif
371     }
372
373     void
(gdb) c
Continuing.

Thread 1 "gzdoom" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
```

Stacktrace/Call chain:

```
#1  0xf7b60db0 in X11_Xinput2GrabTouch (_this=0x5b63d920, window=0x5bd2bab0) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/x11/SDL_x11xinput2.c:369
369         X11_XIGrabTouchBegin(display, XIAllDevices, data->xwindow, True, &eventmask, 1, &mods);
(gdb) 
#2  0xf7b5f390 in X11_SetWindowMouseGrab (_this=0x5b63d920, window=0x5bd2bab0, grabbed=SDL_FALSE) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/x11/SDL_x11window.c:1787
1787            X11_Xinput2GrabTouch(_this, window);
(gdb) 
#3  0xf7b3073c in SDL_UpdateWindowGrab (window=0x5bd2bab0) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:2816
2816            _this->SetWindowMouseGrab(_this, window, mouse_grabbed);
(gdb) 
#4  0xf7b5e959 in X11_BeginWindowFullscreenLegacy (_this=0x5b63d920, window=0x5bd2bab0, _display=0x5b5cfe30) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/x11/SDL_x11window.c:1511
1511        SDL_UpdateWindowGrab(window);
(gdb) 
#5  0xf7b5ec1e in X11_SetWindowFullscreen (_this=0x5b63d920, window=0x5bd2bab0, _display=0x5b5cfe30, fullscreen=SDL_TRUE) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/x11/SDL_x11window.c:1581
1581                X11_BeginWindowFullscreenLegacy(_this, window, _display);
(gdb) 
#6  0xf7b2ce0d in SDL_UpdateFullscreenMode (window=0x5bd2bab0, fullscreen=SDL_TRUE) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:1357
1357                        _this->SetWindowFullscreen(_this, other, display, SDL_TRUE);
(gdb) 
#7  0xf7b30eed in SDL_OnWindowRestored (window=0x5bd2bab0) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:2998
2998            SDL_UpdateFullscreenMode(window, SDL_TRUE);
(gdb) 
#8  0xf7b30d5f in SDL_OnWindowShown (window=0x5bd2bab0) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:2944
2944        SDL_OnWindowRestored(window);
(gdb) 
#9  0xf7a46b1e in SDL_SendWindowEvent (window=0x5bd2bab0, windowevent=1 '\001', data1=0, data2=0) at /usr/src/debug/SDL2-2.0.22-0.i386/src/events/SDL_windowevents.c:89
89              SDL_OnWindowShown(window);
(gdb) 
#10 0xf7b2f457 in SDL_ShowWindow_REAL (window=0x5bd2bab0) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:2370
2370        SDL_SendWindowEvent(window, SDL_WINDOWEVENT_SHOWN, 0, 0);
(gdb) 
#11 0xf7b2d0e4 in SDL_FinishWindowCreation (window=0x5bd2bab0, flags=4259) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:1463
1463            SDL_ShowWindow(window);
(gdb) 
#12 0xf7b2d7f4 in SDL_CreateWindow_REAL (title=0x5baa94cc "GZDoom 4.8.1 ()", x=805240832, y=805240832, w=1920, h=1056, flags=4259) at /usr/src/debug/SDL2-2.0.22-0.i386/src/video/SDL_video.c:1672
1672        SDL_FinishWindowCreation(window, flags);
(gdb) 
#13 0xf7a35d81 in SDL_CreateWindow (a=0x5baa94cc "GZDoom 4.8.1 ()", b=805240832, c=805240832, d=1920, e=1056, f=4259) at /usr/src/debug/SDL2-2.0.22-0.i386/src/dynapi/SDL_dynapi_procs.h:542
542     SDL_DYNAPI_PROC(SDL_Window*,SDL_CreateWindow,(const char *a, int b, int c, int d, int e, Uint32 f),(a,b,c,d,e,f),return)
```

**Comment by jengelh** [comment]
libXi.so.6 was absent, and SDL did not complain about it :-/

**Comment by icculus** [comment]
I don't have a touch setup at the moment, but the fix is obvious and straightforward...so let me know if fdb86b8266947e225f058b32ebb77fa949f6ae42 doesn't solve the problem.
