### ISSUE TITLE
wayland: Crash in Wayland_ShowWindow when fallbacking maximized window to libdecor in xdg-decoration handler

### ISSUE THREAD

**Issue by dos1** [libsdl-org/SDL#5952]
The code from 6f88cbe4c9190e8f91ad6b232fe1705ba7d1c508 ends up segfaulting:

```
(gdb) bt
#0  0x00007ffff7c1c964 in wl_proxy_get_version () from /usr/lib/libwayland-client.so.0
#1  0x00007ffff7fb5bb0 in xdg_toplevel_set_maximized (xdg_toplevel=0x0) at src/xdg-shell-client-protocol.h:1809
#2  0x00007ffff7fb7376 in libdecor_frame_set_maximized (frame=0x555555873730) at ../src/libdecor.c:951
#3  0x0000555555604647 in Wayland_MaximizeWindow (_this=_this@entry=0x555555734870, window=window@entry=0x555555837010) at /home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:1739
#4  0x0000555555604e0b in Wayland_ShowWindow (_this=0x555555734870, window=0x555555837010) at /home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:1288
#5  0x00005555555da957 in SDL_ShowWindow_REAL (window=0x555555837010) at /home/dos/git/SDL/src/video/SDL_video.c:2387
#6  0x00007ffff75c2536 in ffi_call_unix64 () at ../src/x86/unix64.S:105
#7  0x00007ffff75bf037 in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:672
#8  0x00007ffff7c1c5e2 in ?? () from /usr/lib/libwayland-client.so.0
#9  0x00007ffff7c1cd73 in ?? () from /usr/lib/libwayland-client.so.0
#10 0x00007ffff7c1cf8c in wl_display_dispatch_queue_pending () from /usr/lib/libwayland-client.so.0
#11 0x0000555555689fa0 in Wayland_PumpEvents (_this=<optimized out>) at /home/dos/git/SDL/src/video/wayland/SDL_waylandevents.c:372
#12 0x000055555559a453 in SDL_PumpEventsInternal (push_sentinel=SDL_TRUE) at /home/dos/git/SDL/src/events/SDL_events.c:858
#13 0x000055555559a68a in SDL_WaitEventTimeout_REAL (event=0x7fffffffd1d0, timeout=0) at /home/dos/git/SDL/src/events/SDL_events.c:1038
#14 0x00005555555807d0 in main (argc=<optimized out>, argv=<optimized out>) at /home/dos/git/SDL/test/testgl2.c:389
```

A simple way to reproduce:
1. Use [phoc](https://gitlab.gnome.org/World/Phosh/phoc) as the compositor - it automatically maximizes client windows by default.
2. Apply this patch to phoc to make it force CSD on clients:
```diff
--- a/src/xdg_shell.c
+++ b/src/xdg_shell.c
@@ -438,7 +438,7 @@ static void decoration_handle_request_mode(struct wl_listener *listener,
        if (mode == WLR_XDG_TOPLEVEL_DECORATION_V1_MODE_NONE) {
                mode = WLR_XDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE;
        }
-       wlr_xdg_toplevel_decoration_v1_set_mode(decoration->wlr_decoration, mode);
+       wlr_xdg_toplevel_decoration_v1_set_mode(decoration->wlr_decoration, WLR_XDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE);
 }
 
 static void decoration_handle_surface_commit(struct wl_listener *listener,
```
3. Run `./testgl2 --resizable`

Alternatively, run `./testgl2 --resizable --maximize` on some other compositor that forces CSD via xdg-decoration.

Could possibly be a libdecor bug too.

**Comment by flibitijibibo** [comment]
Could be vaguely related: #5672
