### ISSUE TITLE
E/JavaBinder(  868): !!! FAILED BINDER TRANSACTION !!!

### ISSUE THREAD

**Issue by Ratstail91** [libsdl-org/SDL#6519]
I'm at a total loss as to why this is crashing, and I've given up after hours of trying - any help is greatly appreciated.

As far as I can tell, the "Intent" thing is too big, causing a `TransactionTooLargeException` - but I can't tell what is going on at all.

Platform: OPPO1601, Android 5.1 (extremely outdated, but only option I have ATM)
Project: Trying to get [this](https://github.com/Ratstail91/airport) to run on the phone
Error (logs are massive, but here's a snippet):

```
V/WindowManager(  868): Changing focus from Window{809aadd u0 com.krgamestudios.airport/com.krgamestudios.airport.airportActivity} to
null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4927 com.android.server.am.ActivityManagerService.setFocusedActi
vityLocked:3085 com.android.server.am.ActivityStack.adjustFocusedActivityLocked:3137 com.android.server.am.ActivityStack.finishActivit
yLocked:3451
I/WindowManager(  868): Losing focus: Window{809aadd u0 com.krgamestudios.airport/com.krgamestudios.airport.airportActivity}
E/JavaBinder(  868): !!! FAILED BINDER TRANSACTION !!!
I/art     (  868): [heap] RegisterNativeAllocation start bytes:1047552
I/art     (  868): [heap] RegisterNativeAllocation RunFinalization time 1
I/art     (  868): [heap] RegisterNativeAllocation native_bytes_allocated_:0
I/art     (  868): [heap] RegisterNativeAllocation new_native_bytes_allocated:0, native_bytes_allocated_:1047552, native_footprint_gc_
watermark_:4194304, growth_limit_:536870912
E/JavaBinder(  868): !!! FAILED BINDER TRANSACTION !!!
W/ActivityManager(  868): Exception thrown during pause
W/ActivityManager(  868): android.os.TransactionTooLargeException
W/ActivityManager(  868):       at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  868):       at android.os.BinderProxy.transact(Binder.java:504)
W/ActivityManager(  868):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:763)
W/ActivityManager(  868):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:996)
W/ActivityManager(  868):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3469)
W/ActivityManager(  868):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3272)
W/ActivityManager(  868):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSuperviso
r.java:3242)
W/ActivityManager(  868):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:14483
)
W/ActivityManager(  868):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:1437
4)
W/ActivityManager(  868):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:15130)
W/ActivityManager(  868):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.jav
a:14581)
W/ActivityManager(  868):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by 1bsyl** [comment]
@Ratstail91 this is more a log of android system stuff than SDL. try to grab the SDL traces. enable more trace if possible. make sure SDL is up to date.

**Comment by 1bsyl** [comment]
not an sdl issue
