### ISSUE TITLE
Segfault at game shutdown, when running inside firejail.

### ISSUE THREAD

**Issue by bernhardu** [libsdl-org/SDL#6548]
Hello, I just want to report that I receive a segfault when running Xonotic inside firejail and when I want to exit the game. The game is working fine before for me otherwise.

I guess related to this is this message at startup:
```
Failed to init SDL joystick subsystem: Could not initialize UDEV
```

When I leave the game I get this segfault:
```
Core was generated by `./xonotic-linux64-sdl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f709817815a in SDL_UDEV_DelCallback (cb=cb@entry=0x7f7098173980 <joystick_udev_callback>) at ./src/core/linux/SDL_udev.c:547
547     ./src/core/linux/SDL_udev.c: Datei oder Verzeichnis nicht gefunden.
[Current thread is 1 (Thread 0x7f7096fe0e00 (LWP 10))]
(gdb) bt
#0  0x00007f709817815a in SDL_UDEV_DelCallback (cb=cb@entry=0x7f7098173980 <joystick_udev_callback>) at ./src/core/linux/SDL_udev.c:547
#1  0x00007f7098173814 in LINUX_JoystickQuit () at ./src/joystick/linux/SDL_sysjoystick.c:1696
#2  0x00007f709809d645 in SDL_JoystickQuit () at ./src/joystick/SDL_joystick.c:1213
#3  0x00007f709806b19d in SDL_QuitSubSystem_REAL (flags=flags@entry=62001) at ./src/SDL.c:393
#4  0x00007f709806b4f8 in SDL_Quit_REAL () at ./src/SDL.c:488
#5  0x000056320c521485 in Host_Shutdown () at ../../../host.c:1458
#6  0x000056320c65e319 in Sys_Quit () at ../../../sys_shared.c:54
#7  0x000056320c486288 in Cmd_ExecuteString () at ../../../cmd.c:1938
#8  0x000056320c4869c1 in Cbuf_Execute () at ../../../cmd.c:361
#9  0x000056320c486bf5 in Cbuf_Frame () at ../../../cmd.c:383
#10 0x000056320c520bd9 in Host_Main () at ../../../host.c:781
#11 0x000056320c3ed6d5 in main () at ../../../sys_sdl.c:249
(gdb) print _this
$1 = (SDL_UDEV_PrivateData *) 0x0
```

https://github.com/libsdl-org/SDL/blob/78ea6af2cddfa050a394ff9030d0ddd631099848/src/core/linux/SDL_udev.c#L542-L549
[Debian source: src/core/linux/SDL_udev.c:547](https://sources.debian.org/src/libsdl2/2.24.2%2Bdfsg-1/src/core/linux/SDL_udev.c/#L547)

I am just opening this issue to ask if it might be a good idea to
leave `SDL_UDEV_DelCallback` early if `_this == NULL`?

**Comment by sezero** [comment]
Indeed. @slouken: The following OK? (Also for 2.24.x)
```diff

diff --git a/src/core/linux/SDL_udev.c b/src/core/linux/SDL_udev.c
index 311cdd1..85cde89 100644
--- a/src/core/linux/SDL_udev.c
+++ b/src/core/linux/SDL_udev.c
@@ -543,10 +543,14 @@ void
 SDL_UDEV_DelCallback(SDL_UDEV_Callback cb)
 {
     SDL_UDEV_CallbackList *item;
     SDL_UDEV_CallbackList *prev = NULL;
 
+    if (_this == NULL) {
+        return;
+    }
+
     for (item = _this->first; item != NULL; item = item->next) {
         /* found it, remove it. */
         if (item->callback == cb) {
             if (prev != NULL) {
                 prev->next = item->next;
```

**Comment by slouken** [comment]
Yup, that's fine, for both branches. Thanks!

**Comment by sezero** [comment]
Done.

**Comment by bernhardu** [comment]
Wow, that was fast. Thanks.
