### ISSUE TITLE
Moving window on a touchscreen causes segfault on wayland

### ISSUE THREAD

**Issue by soyersoyer** [libsdl-org/SDL#7726]
I tried to move a simple example window on the title bar by touch.

bt:
```
Thread 1 "rust" received signal SIGSEGV, Segmentation fault.
0x00007ffff7eef54f in SDL_ceilf_REAL (x=<error reading variable: Cannot access memory at address 0x7fff00001004>)
    at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/stdlib/SDL_stdlib.c:149
149         return ceilf(x);                                                                                                                                               
(gdb) bt
#0  0x00007ffff7eef54f in SDL_ceilf_REAL (x=Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x7fff00001004
#1  wayland_get_system_cursor (scale=<synthetic pointer>, cdata=0x5555555d6700, vdata=0x5555555ce890)
    at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/video/wayland/SDL_waylandmouse.c:204
#2  Wayland_ShowCursor (cursor=<optimized out>) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/video/wayland/SDL_waylandmouse.c:516
#3  0x00007ffff7f2ad44 in SDL_UpdateMouseFocus.isra.0
    (window=window@entry=0x5555557ab090, x=0, y=0, send_mouse_motion=send_mouse_motion@entry=SDL_TRUE, buttonstate=<optimized out>)
    at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/events/SDL_mouse.c:362
#4  0x00007ffff7f1f62a in SDL_PrivateSendMouseButton.constprop.0.isra.0
    (window=0x5555557ab090, mouseID=4294967295, state=<optimized out>, button=<optimized out>, clicks=-1)
    at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/events/SDL_mouse.c:756
#5  0x00007ffff7f2aff8 in SDL_SendMouseButton (button=1 '\001', state=1 '\001', mouseID=4294967295, window=0x5555557ab090)
    at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/events/SDL_mouse.c:827
#6  SDL_SendTouch.isra.0 (id=93824992761904, fingerid=0, window=0x5555557ab090, down=SDL_TRUE, x=3899830.75, y=2.66246708e-44, pressure=1)
    at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/events/SDL_touch.c:287
#7  0x00007ffff7fb2be6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#8  0x00007ffff7faf4bf in ffi_call_int (cif=cif@entry=0x7fffffffcc00, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0)
    at ../src/x86/ffi64.c:673
#9  0x00007ffff7fb218e in ffi_call (cif=cif@entry=0x7fffffffcc00, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7fffffffccd0)
    at ../src/x86/ffi64.c:710
#10 0x00007ffff787ff0e in wl_closure_invoke (closure=closure@entry=0x55555616ee40, target=<optimized out>, 
    target@entry=0x5555555d5830, opcode=opcode@entry=0, data=<optimized out>, flags=1) at ../src/connection.c:1025
#11 0x00007ffff7880793 in dispatch_event (display=display@entry=0x5555555ca6e0, queue=0x5555555ca7d0) at ../src/wayland-client.c:1631
#12 0x00007ffff7880a3c in dispatch_queue (queue=0x5555555ca7d0, display=0x5555555ca6e0) at ../src/wayland-client.c:1777
#13 wl_display_dispatch_queue_pending (display=0x5555555ca6e0, queue=0x5555555ca7d0) at ../src/wayland-client.c:2019
#14 0x00007ffff7eec598 in Wayland_PumpEvents (_this=<optimized out>) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/video/wayland/SDL_waylandevents.c:386
#15 0x00007ffff7e246f0 in SDL_PumpEventsInternal (push_sentinel=push_sentinel@entry=SDL_TRUE) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/events/SDL_events.c:867
#16 0x00007ffff7e24ade in SDL_WaitEventTimeout_REAL (event=0x7fffffffd028, timeout=0) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/events/SDL_events.c:1046
#17 0x000055555556b719 in sdl2::event::poll_event () at src/sdl2/event.rs:2527
#18 0x000055555556b7d6 in sdl2::event::{impl#9}::next (self=0x7fffffffd658) at src/sdl2/event.rs:2676
#19 0x000055555555f8dc in rust::main () at src/main.rs:54
#20 0x0000555555560242 in core::ops::function::FnOnce::call_once<fn() -> core::result::Result<(), alloc::string::String>, ()> ()
    at /builddir/build/BUILD/rustc-1.69.0-src/library/core/src/ops/function.rs:250
#21 0x000055555555fa65 in std::sys_common::backtrace::__rust_begin_short_backtrace<fn() -> core::result::Result<(), alloc::string::String>, core::result::Result<(), alloc::string::String>> (f=0x55555555ef10 <rust::main>) at /builddir/build/BUILD/rustc-1.69.0-src/library/std/src/sys_common/backtrace.rs:134
#22 0x000055555555ec16 in std::rt::lang_start::{closure#0}<core::result::Result<(), alloc::string::String>> ()
    at /builddir/build/BUILD/rustc-1.69.0-src/library/std/src/rt.rs:166
#23 0x000055555558473c in std::rt::lang_start_internal::h0806e8cf8d03fea8 ()
#24 0x000055555555ebea in std::rt::lang_start<core::result::Result<(), alloc::string::String>> (main=0x55555555ef10 <rust::main>, argc=1, argv=0x7fffffffda78, sigpipe=0)
    at /builddir/build/BUILD/rustc-1.69.0-src/library/std/src/rt.rs:165
#25 0x000055555555fa4e in main ()
#26 0x00007ffff7bfab4a in __libc_start_call_main (main=main@entry=0x55555555fa30 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffda78)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#27 0x00007ffff7bfac0b in __libc_start_main_impl
    (main=0x55555555fa30 <main>, argc=1, argv=0x7fffffffda78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda68)
    at ../csu/libc-start.c:360
#28 0x000055555555e435 in _start ()
```

**Comment by Kontrabant** [comment]
Looking at the touch code, there is currently no validation being done to ensure that the surface corresponds to an SDL window, which can be a problem if using libraries like libdecor, which creates its own subsurfaces for the decorations and drop shadows. Touch events will be sent, but, as SDL doesn't own the surface and never set the appropriate user data, whatever pointer is being passed for an SDL window isn't actually a pointer to an SDL window.

I'll look into this.

**Comment by Kontrabant** [comment]
Reopening until this is backported to SDL2.

**Comment by soyersoyer** [comment]
I tried it with SDL3, it doesn't crash anymore. Thanks.
