### ISSUE TITLE
Porting to android, java.lang.UnsatisfiedLinkError: No implementation found for int org.libsdl.app.SDLActivity.nativeCheckSDLThreadCounter()

### ISSUE THREAD

**Issue by koogelpotato** [libsdl-org/SDL#7908]
Hello, I'm trying to port my application to Android, my project builds and compiles, but when I try to launch it, my application crashes immediately, logcat prints this:
```
FATAL EXCEPTION: SDLActivity
                                                                                                    Process: org.koogel, PID: 4486
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for int org.libsdl.app.SDLActivity.nativeCheckSDLThreadCounter() (tried Java_org_libsdl_app_SDLActivity_nativeCheckSDLThreadCounter and Java_org_libsdl_app_SDLActivity_nativeCheckSDLThreadCounter__) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at org.libsdl.app.SDLActivity.nativeCheckSDLThreadCounter(Native Method)
                                                                                                    	at org.libsdl.app.SDLActivity.onCreate(SDLActivity.java:405)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8176)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
``` 
Checked SDLActivity and it has this error:
`Cannot resolve corresponding JNI function Java_org_libsdl_app_SDLActivity_nativeCheckSDLThreadCounter.`

**Comment by madebr** [comment]
Make sure the SDL3 c and java sources come from the same git commit.
I don't think we promise compatibility between different versions/commits.

I just tested running a SDL test app using https://github.com/libsdl-org/SDL/pull/7581, which work fine.
[download link](https://github.com/libsdl-org/SDL/actions/runs/5437939574?pr=7581)

**Comment by 1bsyl** [comment]
yes, check the SDL lib code you're using, does it have the nativeCheckSDLThreadCounter ? cleanup the build maybe

**Comment by koogelpotato** [comment]
Ok, It seemed that I had a newer version of SDL, compared to the project I was working with, now I will remake it with a newer version, thanks for your help
