### ISSUE TITLE
[SDL3] pulseaudio occasionally fails an assertion

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8348]
With #8347 applied, `test/testautomation --filter audio` occasionally fails with the following message:
```
Assertion '!e->dead' failed at ../src/pulse/mainloop.c:207, function mainloop_io_free(). Aborting.
```
[This location](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/0edcf725bcb77c5a3ae0c3473b775a85dbcd0236/src/pulse/mainloop.c#L207)

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007ffff7ab08f3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7a5fafe in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7a4887f in __GI_abort () at abort.c:79
#4  0x00007ffff693844d in mainloop_io_free (e=<optimized out>) at ../src/pulse/mainloop.c:207
#5  0x00007ffff68c1c81 in delete_events (io=io@entry=0x7fffec007220) at ../src/pulsecore/iochannel.c:66
#6  0x00007ffff68c21ea in pa_iochannel_free (io=0x7fffec007220) at ../src/pulsecore/iochannel.c:186
#7  0x00007ffff68e1e8d in pa_pstream_unlink (p=0x7fffec00f1b0) at ../src/pulsecore/pstream.c:1214
#8  pa_pstream_unlink (p=0x7fffec00f1b0) at ../src/pulsecore/pstream.c:1192
#9  0x00007ffff692d294 in context_unlink (c=c@entry=0x4ca0a0) at ../src/pulse/context.c:234
#10 0x00007ffff692da68 in pa_context_set_state (c=0x4ca0a0, st=PA_CONTEXT_TERMINATED) at ../src/pulse/context.c:323
#11 0x00007ffff7dda17b in DisconnectFromPulseServer ()
    at /home/maarten/programming/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:311
#12 0x00007ffff7ddbcfa in PULSEAUDIO_Deinitialize ()
    at /home/maarten/programming/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:980
#13 0x00007ffff7c2ebf3 in SDL_QuitAudio () at /home/maarten/programming/SDL/src/audio/SDL_audio.c:777
#14 0x00007ffff7c2a4ec in SDL_QuitSubSystem_REAL (flags=16400) at /home/maarten/programming/SDL/src/SDL.c:414
#15 0x00007ffff7c500e8 in SDL_QuitSubSystem (a=16) at /home/maarten/programming/SDL/src/dynapi/SDL_dynapi_procs.h:580
#16 0x0000000000408dda in audio_initQuitAudio (arg=0x0)
    at /home/maarten/programming/SDL/test/testautomation_audio.c:123
#17 0x000000000043dd79 in SDLTest_RunTest
    (testSuite=0x487d00 <audioTestSuite>, testCase=0x442800 <audioTest13>, execKey=10999407525295588986, forceTestRun=SDL_FALSE) at /home/maarten/programming/SDL/src/test/SDL_test_harness.c:271
#18 0x000000000043e730 in SDLTest_RunSuites
    (testSuites=0x487ae0 <testSuites>, userRunSeed=0x0, userExecKey=0, filter=0x48b400 "audio", testIterations=1)
    at /home/maarten/programming/SDL/src/test/SDL_test_harness.c:592
#19 0x0000000000408b93 in main (argc=3, argv=0x7fffffffdc88)
    at /home/maarten/programming/SDL/test/testautomation.c:153
```

<details>

<summary>Full backtrace</summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {1}}
        ret = <optimized out>
#1  0x00007ffff7ab08f3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7a5fafe in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007ffff7a4887f in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {140737330395582, 0, 18446744073709551480, 88, 140737152840000, 140737354125312, 0, 140737488344864, 140737348629006, 0, 0, 0, 140737152840016, 140737353491384, 88, 140737488344912}}, sa_flags = -157998164, sa_restorer = 0x7fffffffd760}
#4  0x00007ffff693844d in mainloop_io_free (e=<optimized out>) at ../src/pulse/mainloop.c:207
        __func__ = "mainloop_io_free"
        __PRETTY_FUNCTION__ = "mainloop_io_free"
#5  0x00007ffff68c1c81 in delete_events (io=io@entry=0x7fffec007220) at ../src/pulsecore/iochannel.c:66
        __func__ = "delete_events"
        __PRETTY_FUNCTION__ = "delete_events"
#6  0x00007ffff68c21ea in pa_iochannel_free (io=0x7fffec007220) at ../src/pulsecore/iochannel.c:186
        __func__ = "pa_iochannel_free"
        __PRETTY_FUNCTION__ = "pa_iochannel_free"
#7  0x00007ffff68e1e8d in pa_pstream_unlink (p=0x7fffec00f1b0) at ../src/pulsecore/pstream.c:1214
        __func__ = "pa_pstream_unlink"
        __PRETTY_FUNCTION__ = "pa_pstream_unlink"
#8  pa_pstream_unlink (p=0x7fffec00f1b0) at ../src/pulsecore/pstream.c:1192
        __func__ = "pa_pstream_unlink"
        __PRETTY_FUNCTION__ = "pa_pstream_unlink"
#9  0x00007ffff692d294 in context_unlink (c=c@entry=0x4ca0a0) at ../src/pulse/context.c:234
        s = <optimized out>
        __func__ = "context_unlink"
        __PRETTY_FUNCTION__ = "context_unlink"
#10 0x00007ffff692da68 in pa_context_set_state (c=0x4ca0a0, st=PA_CONTEXT_TERMINATED) at ../src/pulse/context.c:323
        __func__ = "pa_context_set_state"
        __PRETTY_FUNCTION__ = "pa_context_set_state"
#11 0x00007ffff7dda17b in DisconnectFromPulseServer () at /home/maarten/programming/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:311
#12 0x00007ffff7ddbcfa in PULSEAUDIO_Deinitialize () at /home/maarten/programming/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:980
#13 0x00007ffff7c2ebf3 in SDL_QuitAudio () at /home/maarten/programming/SDL/src/audio/SDL_audio.c:777
        devices = 0x0
        __func__ = "SDL_QuitAudio"
#14 0x00007ffff7c2a4ec in SDL_QuitSubSystem_REAL (flags=16400) at /home/maarten/programming/SDL/src/SDL.c:414
#15 0x00007ffff7c500e8 in SDL_QuitSubSystem (a=16) at /home/maarten/programming/SDL/src/dynapi/SDL_dynapi_procs.h:580
#16 0x0000000000408dda in audio_initQuitAudio (arg=0x0) at /home/maarten/programming/SDL/test/testautomation_audio.c:123
        result = 0
        i = 0
        iMax = 0
        audioDriver = 0x7fffffffd900 "@\331\377\377\377\177"
#17 0x000000000043dd79 in SDLTest_RunTest (testSuite=0x487d00 <audioTestSuite>, testCase=0x442800 <audioTest13>, execKey=10999407525295588986, forceTestRun=SDL_FALSE) at /home/maarten/programming/SDL/src/test/SDL_test_harness.c:271
        timer = 12
        testCaseResult = 0
        testResult = 0
        fuzzerCount = 5
#18 0x000000000043e730 in SDLTest_RunSuites (testSuites=0x487ae0 <testSuites>, userRunSeed=0x0, userExecKey=0, filter=0x48b400 "audio", testIterations=1) at /home/maarten/programming/SDL/src/test/SDL_test_harness.c:592
        totalNumberOfTests = 306
        failedNumberOfTests = 0
        suiteCounter = 1
        testCounter = 13
        iterationCounter = 1
        testSuite = 0x487d00 <audioTestSuite>
        testCase = 0x442800 <audioTest13>
        runSeed = 0x7fffffffd980 "41L4Y49ZOJCSCGXP"
        currentSuiteName = 0x442aa0 "Audio"
        currentTestName = 0x4427c0 "audio_initQuitAudio"
        execKey = 10999407525295588986
        runStartSeconds = 49003.668
        suiteStartSeconds = 49003.668
        testStartSeconds = 49003.9258
        runEndSeconds = 4.59163468e-41
        suiteEndSeconds = 0
        testEndSeconds = 49003.9258
        runtime = 0.015625
        suiteFilter = 1
        suiteFilterName = 0x442aa0 "Audio"
        testFilter = 0
        testFilterName = 0x0
        forceTestRun = SDL_FALSE
        testResult = 0
        runResult = 0
        totalTestFailedCount = 0
        totalTestPassedCount = 11
        totalTestSkippedCount = 1
        testFailedCount = 0
        testPassedCount = 11
        testSkippedCount = 1
        countSum = 0
        failedTests = 0x4d1000
        generatedSeed = "41L4Y49ZOJCSCGXP"
#19 0x0000000000408b93 in main (argc=3, argv=0x7fffffffdc88) at /home/maarten/programming/SDL/test/testautomation.c:153
        result = 0
        testIterations = 1
        userExecKey = 0
        userRunSeed = 0x0
        filter = 0x48b400 "audio"
        i = 0
        done = 0
        event = {type = 64, common = {type = 64, timestamp = 6291456}, display = {type = 64, timestamp = 6291456, displayID = 12, data1 = 0}, window = {type = 64, timestamp = 6291456, windowID = 12, data1 = 0, data2 = 0}, key = {type = 64, timestamp = 6291456, windowID = 12, state = 0 '\000', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 8, unused = 0}}, edit = {type = 64, timestamp = 6291456, windowID = 12, text = '\000' <repeats 12 times>, "\b\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000@\000\000", start = 0, length = 8}, editExt = {type = 64, timestamp = 6291456, windowID = 12, text = 0x0, start = 8, length = 0}, text = {type = 64, timestamp = 6291456, windowID = 12, text = '\000' <repeats 12 times>, "\b\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000@\000\000"}, motion = {type = 64, timestamp = 6291456, windowID = 12, which = 0, state = 0, x = 0, y = 1.12103877e-44, xrel = 0, yrel = 3.67341985e-40}, button = {type = 64, timestamp = 6291456, windowID = 12, which = 0, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding = 0 '\000', x = 0, y = 1.12103877e-44}, wheel = {type = 64, timestamp = 6291456, windowID = 12, which = 0, x = 0, y = 0, direction = 8, mouseX = 0, mouseY = 3.67341985e-40}, jaxis = {type = 64, timestamp = 6291456, which = 12, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jhat = {type = 64, timestamp = 6291456, which = 12, hat = 0 '\000', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 64, timestamp = 6291456, which = 12, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 64, timestamp = 6291456, which = 12}, jbattery = {type = 64, timestamp = 6291456, which = 12, level = SDL_JOYSTICK_POWER_EMPTY}, gaxis = {type = 64, timestamp = 6291456, which = 12, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, gbutton = {type = 64, timestamp = 6291456, which = 12, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, gdevice = {type = 64, timestamp = 6291456, which = 12}, gtouchpad = {type = 64, timestamp = 6291456, which = 12, touchpad = 0, finger = 0, x = 0, y = 1.12103877e-44, pressure = 0}, gsensor = {type = 64, timestamp = 6291456, which = 12, sensor = 0, data = {0, 0, 1.12103877e-44}, sensor_timestamp = 262144}, adevice = {type = 64, timestamp = 6291456, which = 12, iscapture = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, sensor = {type = 64, timestamp = 6291456, which = 12, data = {0, 0, 0, 1.12103877e-44, 0, 3.67341985e-40}, sensor_timestamp = 64}, quit = {type = 64, timestamp = 6291456}, user = {type = 64, timestamp = 6291456, windowID = 12, code = 0, data1 = 0x0, data2 = 0x8}, syswm = {type = 64, timestamp = 6291456, msg = 0xc}, tfinger = {type = 64, timestamp = 6291456, touchId = 12, fingerId = 0, x = 1.12103877e-44, y = 0, dx = 3.67341985e-40, dy = 0, pressure = 8.96831017e-44, windowID = 0}, drop = {type = 64, timestamp = 6291456, file = 0xc <error: Cannot access memory at address 0xc>, windowID = 0, x = 0, y = 1.12103877e-44}, clipboard = {type = 64, timestamp = 6291456}, padding = "@\000\000\000\000\000\000\000\000\000`\000\000\000\000\000\f", '\000' <repeats 15 times>, "\b\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000@\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000\004\000\000\000\000\000\000\001\000\000\000\000\000\000\000\b\000\000\000\000\000\000\030\333\377\377\377\177\000\000\006\000\000\000<\000\000\000\003\000\000\000\b\000\000"}
        list = 0
```

</details>

**Comment by icculus** [comment]
I can't get this to reproduce here, but it looks pretty clearly like a race condition, so that doesn't mean much.

Does this patch fix it for you?

```diff
diff --git a/src/audio/pulseaudio/SDL_pulseaudio.c b/src/audio/pulseaudio/SDL_pulseaudio.c
index a554fcd32..1ab099baa 100644
--- a/src/audio/pulseaudio/SDL_pulseaudio.c
+++ b/src/audio/pulseaudio/SDL_pulseaudio.c
@@ -307,13 +307,15 @@ static void WaitForPulseOperation(pa_operation *o)
 
 static void DisconnectFromPulseServer(void)
 {
+    if (pulseaudio_threaded_mainloop != NULL) {
+        PULSEAUDIO_pa_threaded_mainloop_stop(pulseaudio_threaded_mainloop);
+    }
     if (pulseaudio_context) {
         PULSEAUDIO_pa_context_disconnect(pulseaudio_context);
         PULSEAUDIO_pa_context_unref(pulseaudio_context);
         pulseaudio_context = NULL;
     }
     if (pulseaudio_threaded_mainloop != NULL) {
-        PULSEAUDIO_pa_threaded_mainloop_stop(pulseaudio_threaded_mainloop);
         PULSEAUDIO_pa_threaded_mainloop_free(pulseaudio_threaded_mainloop);
         pulseaudio_threaded_mainloop = NULL;
     }
```

**Comment by madebr** [comment]
With #8347 applied, running `test/testautomation --filter audio --iterations 100`, I no longer get an assertion failure, but the testautomation program blocks.
I retrieved the following backtrace:
```
#0  0x00007f7a8f2ab219 in __futex_abstimed_wait_common64
    (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x1d42e68) at futex-internal.c:57
#1  __futex_abstimed_wait_common
    (futex_word=futex_word@entry=0x1d42e68, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f7a8f2ab29f in __GI___futex_abstimed_wait_cancelable64
    (futex_word=futex_word@entry=0x1d42e68, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f7a8f2adbb9 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x1d42e68, cond=0x1d42e40)
    at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=cond@entry=0x1d42e40, mutex=mutex@entry=0x1d42e18) at pthread_cond_wait.c:618
#5  0x00007f7a8d4a50db in pw_thread_loop_wait (loop=0x1d42df0) at ../src/pipewire/thread-loop.c:429
#6  0x00007f7a8d3a937a in do_sync (client=0x1d1aaa0) at ../pipewire-jack/src/pipewire-jack.c:1235
#7  0x00007f7a8d3b5ac6 in jack_connect
    (client=0x1d1aaa0, source_port=0x1f4e8b0 "SDL Application:sdl_jack_output_0", destination_port=0x7f7a7c3aa0d0 "Built-in Audio Analog Stereo:playback_FL") at ../pipewire-jack/src/pipewire-jack.c:5714
#8  0x00007f7a8f5d3f60 in JACK_OpenDevice (device=0x1d3bb10)
    at /home/maarten/projects/SDL/src/audio/jack/SDL_jackaudio.c:361
#9  0x00007f7a8f430b12 in OpenPhysicalAudioDevice (device=0x1d3bb10, inspec=0x7ffd41f2ee28)
    at /home/maarten/projects/SDL/src/audio/SDL_audio.c:1422
#10 0x00007f7a8f430e36 in SDL_OpenAudioDevice_REAL (devid=3, spec=0x7ffd41f2ee28)
    at /home/maarten/projects/SDL/src/audio/SDL_audio.c:1505
#11 0x00007f7a8f453700 in SDL_OpenAudioDevice (a=4294967295, b=0x7ffd41f2ee28)
    at /home/maarten/projects/SDL/src/dynapi/SDL_dynapi_procs.h:931
#12 0x0000000000409152 in audio_initOpenCloseQuitAudio (arg=0x0)
    at /home/maarten/projects/SDL/test/testautomation_audio.c:225
#13 0x000000000043dd79 in SDLTest_RunTest
    (testSuite=0x487d00 <audioTestSuite>, testCase=0x4428a0 <audioTest14>, execKey=12133467481423782942, forceTestRun=SDL_FALSE) at /home/maarten/projects/SDL/src/test/SDL_test_harness.c:271
#14 0x000000000043e730 in SDLTest_RunSuites
    (testSuites=0x487ae0 <testSuites>, userRunSeed=0x0, userExecKey=0, filter=0x1c32400 "audio", testIterations=100)
    at /home/maarten/projects/SDL/src/test/SDL_test_harness.c:592
#15 0x0000000000408b93 in main (argc=5, argv=0x7ffd41f2f1d8)
    at /home/maarten/projects/SDL/test/testautomation.c:153
```

WIth #8347, testautomation will quickly initialize and deinitialize every built-in audio backend, so it's very timing sensitive.

**Comment by icculus** [comment]
Ok, so we seem to have fixed the assert in PulseAudio and have moved on to the JACK backend.

To be clear: this is initializing and opening an audio device 100 times in a row?

**Comment by icculus** [comment]
I managed to trigger this once, with PipeWire's JACK emulation, but never again. I never got it to trigger with the actual JACK daemon, which might not be significant considering how rare it seems anyhow, but seeing as it's hanging up inside of the JACK API and not SDL, I'm wondering if the problem is a bug in pipewire-jack that we're finding through stress-testing, and not SDL.

I'm going to leave this issue open for now, in case I can manage to trigger it a few more times, but we might have gone as far as we can here.

**Comment by icculus** [comment]
Okay, I just hit a point where it will reliably freeze on startup of testaudio with pw-jack, but it doesn't do it with actual jackd.

I'm thinking this is 100% a pipewire bug at this point; it appears to be waiting for a signal on the pipewire mainloop that isn't arriving, which suggests a race condition in their JACK emulation code.

(In addition to the other memory corruption problems you're seeing, I think we have to say this probably isn't our bug.)

**Comment by madebr** [comment]
I've reported the issue upstream: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3585

**Comment by icculus** [comment]
Does this SDL3 patch fix pipwire's JACK implementation for you?

```diff
diff --git a/src/audio/SDL_audio.c b/src/audio/SDL_audio.c
index 331e57c7e..e91855df7 100644
--- a/src/audio/SDL_audio.c
+++ b/src/audio/SDL_audio.c
@@ -569,6 +569,7 @@ static int SDL_AudioWaitDevice_Default(SDL_AudioDevice *device) { return 0; /* n
 static int SDL_AudioPlayDevice_Default(SDL_AudioDevice *device, const Uint8 *buffer, int buffer_size) { return 0; /* no-op. */ }
 static int SDL_AudioWaitCaptureDevice_Default(SDL_AudioDevice *device) { return 0; /* no-op. */ }
 static void SDL_AudioFlushCapture_Default(SDL_AudioDevice *device) { /* no-op. */ }
+static void SDL_AudioDeviceIsReady_Default(SDL_AudioDevice *device) { /* no-op. */ }
 static void SDL_AudioCloseDevice_Default(SDL_AudioDevice *device) { /* no-op. */ }
 static void SDL_AudioDeinitialize_Default(void) { /* no-op. */ }
 static void SDL_AudioFreeDeviceHandle_Default(SDL_AudioDevice *device) { /* no-op. */ }
@@ -612,6 +613,7 @@ static void CompleteAudioEntryPoints(void)
     #define FILL_STUB(x) if (!current_audio.impl.x) { current_audio.impl.x = SDL_Audio##x##_Default; }
     FILL_STUB(DetectDevices);
     FILL_STUB(OpenDevice);
+    FILL_STUB(DeviceIsReady);
     FILL_STUB(ThreadInit);
     FILL_STUB(ThreadDeinit);
     FILL_STUB(WaitDevice);
@@ -1538,12 +1540,13 @@ SDL_AudioDeviceID SDL_OpenAudioDevice(SDL_AudioDeviceID devid, const SDL_AudioSp
 
     if (device) {
         SDL_LogicalAudioDevice *logdev = NULL;
+        const SDL_bool wasnt_opened = !device->currently_opened;
         if (!wants_default && SDL_AtomicGet(&device->zombie)) {
             // uhoh, this device is undead, and just waiting to be cleaned up. Refuse explicit opens.
             SDL_SetError("Device was already lost and can't accept new opens");
         } else if ((logdev = (SDL_LogicalAudioDevice *) SDL_calloc(1, sizeof (SDL_LogicalAudioDevice))) == NULL) {
             SDL_OutOfMemory();
-        } else if (!device->currently_opened && OpenPhysicalAudioDevice(device, spec) == -1) {  // first thing using this physical device? Open at the OS level...
+        } else if (wasnt_opened && OpenPhysicalAudioDevice(device, spec) == -1) {  // first thing using this physical device? Open at the OS level...
             SDL_free(logdev);
         } else {
             RefPhysicalAudioDevice(device);  // unref'd on successful SDL_CloseAudioDevice
@@ -1567,6 +1570,8 @@ SDL_AudioDeviceID SDL_OpenAudioDevice(SDL_AudioDeviceID devid, const SDL_AudioSp
             if (!inserted) {
                 SDL_CloseAudioDevice(retval);
                 retval = 0;
+            } else if (wasnt_opened) {
+                current_audio.impl.DeviceIsReady(device);
             }
         }
     }
diff --git a/src/audio/SDL_sysaudio.h b/src/audio/SDL_sysaudio.h
index c33ac9ce0..b80628d41 100644
--- a/src/audio/SDL_sysaudio.h
+++ b/src/audio/SDL_sysaudio.h
@@ -131,6 +131,7 @@ typedef struct SDL_AudioDriverImpl
 {
     void (*DetectDevices)(SDL_AudioDevice **default_output, SDL_AudioDevice **default_capture);
     int (*OpenDevice)(SDL_AudioDevice *device);
+    void (*DeviceIsReady)(SDL_AudioDevice *device);  // Called after OpenDevice finishes, SDL finishes its Open work, and releases device lock.
     void (*ThreadInit)(SDL_AudioDevice *device);   // Called by audio thread at start
     void (*ThreadDeinit)(SDL_AudioDevice *device); // Called by audio thread at end
     int (*WaitDevice)(SDL_AudioDevice *device);
diff --git a/src/audio/jack/SDL_jackaudio.c b/src/audio/jack/SDL_jackaudio.c
index 4f0691bc3..13ab88682 100644
--- a/src/audio/jack/SDL_jackaudio.c
+++ b/src/audio/jack/SDL_jackaudio.c
@@ -144,33 +144,52 @@ static void jackShutdownCallback(void *arg) /* JACK went away; device is lost. *
 
 static int jackSampleRateCallback(jack_nframes_t nframes, void *arg)
 {
-    //SDL_Log("JACK Sample Rate Callback! %d", (int) nframes);
     SDL_AudioDevice *device = (SDL_AudioDevice *) arg;
-    SDL_AudioSpec newspec;
-    SDL_copyp(&newspec, &device->spec);
-    newspec.freq = (int) nframes;
-    if (SDL_AudioDeviceFormatChanged(device, &newspec, device->sample_frames) < 0) {
-        SDL_AudioDeviceDisconnected(device);
+    //SDL_Log("JACK Sample Rate Callback! %d, ready=%d", (int) nframes, SDL_AtomicGet(&device->hidden->ready));
+    if (SDL_AtomicGet(&device->hidden->ready)) {
+        SDL_AudioSpec newspec;
+        SDL_copyp(&newspec, &device->spec);
+        newspec.freq = (int) nframes;
+        if (SDL_AudioDeviceFormatChanged(device, &newspec, device->sample_frames) < 0) {
+            SDL_AudioDeviceDisconnected(device);
+        }
     }
     return 0;
 }
 
 static int jackBufferSizeCallback(jack_nframes_t nframes, void *arg)
 {
-    //SDL_Log("JACK Buffer Size Callback! %d", (int) nframes);
     SDL_AudioDevice *device = (SDL_AudioDevice *) arg;
-    SDL_AudioSpec newspec;
-    SDL_copyp(&newspec, &device->spec);
-    if (SDL_AudioDeviceFormatChanged(device, &newspec, (int) nframes) < 0) {
-        SDL_AudioDeviceDisconnected(device);
+    //SDL_Log("JACK Buffer Size Callback! %d, ready=%d", (int) nframes, SDL_AtomicGet(&device->hidden->ready));
+    if (SDL_AtomicGet(&device->hidden->ready)) {
+        SDL_AudioSpec newspec;
+        SDL_copyp(&newspec, &device->spec);
+        if (SDL_AudioDeviceFormatChanged(device, &newspec, (int) nframes) < 0) {
+            SDL_AudioDeviceDisconnected(device);
+        }
     }
     return 0;
 }
 
 static int jackProcessPlaybackCallback(jack_nframes_t nframes, void *arg)
 {
-    SDL_assert(nframes == ((SDL_AudioDevice *)arg)->sample_frames);
-    SDL_OutputAudioThreadIterate((SDL_AudioDevice *)arg);
+    SDL_AudioDevice *device = (SDL_AudioDevice *) arg;
+    //SDL_Log("JACK Playback Callback! %d, ready=%d", (int) nframes, SDL_AtomicGet(&device->hidden->ready));
+    if (SDL_AtomicGet(&device->hidden->ready)) {
+        SDL_assert(nframes == device->sample_frames);
+        SDL_OutputAudioThreadIterate((SDL_AudioDevice *)arg);
+    } else {
+        // not ready, just feed silence.
+        jack_port_t **ports = device->hidden->sdlports;
+        const int total_channels = device->spec.channels;
+        for (int channelsi = 0; channelsi < total_channels; channelsi++) {
+            float *dst = (float *)JACK_jack_port_get_buffer(ports[channelsi], nframes);
+            if (dst) {
+                SDL_memset(dst, '\0', nframes * sizeof (float));
+            }
+        }
+    }
+
     return 0;
 }
 
@@ -333,8 +352,6 @@ static int JACK_OpenDevice(SDL_AudioDevice *device)
         return SDL_SetError("No physical JACK ports available");
     }
 
-    /* !!! FIXME: docs say about buffer size: "This size may change, clients that depend on it must register a bufsize_callback so they will be notified if it does." */
-
     /* Jack pretty much demands what it wants. */
     device->spec.format = SDL_AUDIO_F32;
     device->spec.freq = JACK_jack_get_sample_rate(client);
@@ -405,6 +422,21 @@ static int JACK_OpenDevice(SDL_AudioDevice *device)
     return 0;
 }
 
+void JACK_DeviceIsReady(SDL_AudioDevice *device)
+{
+    //SDL_Log("JACK Device is ready!");
+    jack_client_t *client = device->hidden->client;
+    SDL_AudioSpec spec;
+    SDL_copyp(&spec, &device->spec);
+    spec.freq = JACK_jack_get_sample_rate(client);
+    // this is (probably) a no-op, but just in case this changed during startup...
+    if (SDL_AudioDeviceFormatChanged(device, &spec, (int) JACK_jack_get_buffer_size(client)) < 0) {
+        SDL_AudioDeviceDisconnected(device);
+    }
+    SDL_AtomicSet(&device->hidden->ready, 1);
+}
+
+
 static void JACK_Deinitialize(void)
 {
     UnloadJackLibrary();
@@ -427,6 +459,7 @@ static SDL_bool JACK_Init(SDL_AudioDriverImpl *impl)
 
     /* Set the function pointers */
     impl->OpenDevice = JACK_OpenDevice;
+    impl->DeviceIsReady = JACK_DeviceIsReady;
     impl->GetDeviceBuf = JACK_GetDeviceBuf;
     impl->PlayDevice = JACK_PlayDevice;
     impl->CloseDevice = JACK_CloseDevice;
diff --git a/src/audio/jack/SDL_jackaudio.h b/src/audio/jack/SDL_jackaudio.h
index a8cf81d4f..4e4a0432f 100644
--- a/src/audio/jack/SDL_jackaudio.h
+++ b/src/audio/jack/SDL_jackaudio.h
@@ -30,6 +30,7 @@ struct SDL_PrivateAudioData
     jack_client_t *client;
     jack_port_t **sdlports;
     float *iobuffer;
+    SDL_AtomicInt ready;
 };
 
 #endif /* SDL_jackaudio_h_ */
```

**Comment by icculus** [comment]
Actually, it looks like they put a patch into PipeWire, so we're probably good to go here now without that diff. We'll reopen this issue if the PipeWire fix doesn't actually settle the matter.
