### ISSUE TITLE
Segmentation fault when quiting testautomation

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8395]
Since 7f408e57eeb3f194bd7ffaecfc08e1560f2ddc87, when building SDL3 for 32-bit Linux, testautomation segfaults at exit time.
The backtrace is:
```
#0  0xf7aa1736 in pthread_mutex_lock@@GLIBC_2.0 () from /lib/libc.so.6
#1  0xf7e03289 in SDL_LockMutex_REAL (mutex=0x21) at /home/maarten/projects/SDL/src/thread/pthread/SDL_sysmutex.c:91
#2  0xf7c19ef5 in DestroyPhysicalAudioDevice (device=0x80e5040) at /home/maarten/projects/SDL/src/audio/SDL_audio.c:297
#3  0xf7c1b0f1 in SDL_QuitAudio () at /home/maarten/projects/SDL/src/audio/SDL_audio.c:778
#4  0xf7c1663c in SDL_QuitSubSystem_REAL (flags=62001) at /home/maarten/projects/SDL/src/SDL.c:416
#5  0xf7c16850 in SDL_Quit_REAL () at /home/maarten/projects/SDL/src/SDL.c:491
#6  0xf7c3c9e9 in SDL_Quit () at /home/maarten/projects/SDL/src/dynapi/SDL_dynapi_procs.h:563
#7  0x0807ca4f in SDLTest_CommonQuit (state=0x80ca1a0) at /home/maarten/projects/SDL/src/test/SDL_test_common.c:2468
#8  0x0804e71a in quit (rc=0) at /home/maarten/projects/SDL/test/testautomation.c:55
#9  0x0804ebe8 in main (argc=1, argv=0xffffd544) at /home/maarten/projects/SDL/test/testautomation.c:170
#10 0xf7a359b9 in __libc_start_call_main () from /lib/libc.so.6
#11 0xf7a35a7c in __libc_start_main_impl () from /lib/libc.so.6
#12 0x0804e61c in _start ()
```
@icculus

**Comment by madebr** [comment]
It looks like ci also segfaults here.
