### ISSUE TITLE
SDL3 deadlocks when toggling fullscreen in KDE Wayland session with X11 driver.

### ISSUE THREAD

**Issue by Themaister** [libsdl-org/SDL#8842]
To repro:
```
git clone https://github.com/Themaister/Granite
cd Granite
git submodule update --init
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -G Ninja
ninja latency-test
SDL_VIDEO_DRIVER=x11 ./tests/latency-test
```

SDL3 is pulled in as a submodule in third_party/sdl3.

Press Alt + Enter, and UI thread deadlocks in:

```
0x00007ffff7afbf6f in poll () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7afbf6f in poll () from /usr/lib/libc.so.6
#1  0x00007fffdf78720b in ?? () from /usr/lib/libxcb.so.1
#2  0x00007fffdf787910 in ?? () from /usr/lib/libxcb.so.1
#3  0x00007fffdf788ba5 in xcb_wait_for_reply64 () from /usr/lib/libxcb.so.1
#4  0x00007fffdf7eb20d in _XReply () from /usr/lib/libX11.so.6
#5  0x00007fffdf7eb7cd in XTranslateCoordinates () from /usr/lib/libX11.so.6
#6  0x00005555562ae234 in X11_WaitAndSendWindowEvents (window=0x555556c814d0, param_timeout=100, method=COMPARE_DOUBLE_ATTEMPT, orig_x=0, orig_y=0, dest_x=0, dest_y=0, orig_w=2560, orig_h=1440, 
    dest_w=0, dest_h=0) at /tmp/Granite/third_party/sdl3/src/video/x11/SDL_x11window.c:891
#7  0x00005555562b085f in X11_SetWindowFullscreenViaWM (_this=0x555556c2a410, window=0x555556c814d0, _display=0x555556c3b2f0, fullscreen=1)
    at /tmp/Granite/third_party/sdl3/src/video/x11/SDL_x11window.c:1625
#8  0x00005555562b0969 in X11_SetWindowFullscreen (_this=0x555556c2a410, window=0x555556c814d0, _display=0x555556c3b2f0, fullscreen=1)
    at /tmp/Granite/third_party/sdl3/src/video/x11/SDL_x11window.c:1652
#9  0x0000555556219756 in SDL_UpdateFullscreenMode (window=0x555556c814d0, fullscreen=1) at /tmp/Granite/third_party/sdl3/src/video/SDL_video.c:1631
#10 0x000055555621ce0a in SDL_SetWindowFullscreen_REAL (window=0x555556c814d0, fullscreen=1) at /tmp/Granite/third_party/sdl3/src/video/SDL_video.c:2942
#11 0x00005555561c64eb in SDL_SetWindowFullscreen (a=0x555556c814d0, b=1) at /tmp/Granite/third_party/sdl3/src/dynapi/SDL_dynapi_procs.h:666
#12 0x0000555555617ef3 in Granite::WSIPlatformSDL::toggle_fullscreen (this=0x555556c0a5d0) at /tmp/Granite/application/platforms/application_sdl3.cpp:222
#13 0x0000555555619000 in Granite::WSIPlatformSDL::process_sdl_event (this=0x555556c0a5d0, e=...) at /tmp/Granite/application/platforms/application_sdl3.cpp:470
#14 0x00005555556193f0 in Granite::WSIPlatformSDL::iterate_message_loop (this=0x555556c0a5d0) at /tmp/Granite/application/platforms/application_sdl3.cpp:540
#15 0x0000555555618086 in Granite::WSIPlatformSDL::poll_input (this=0x555556c0a5d0) at /tmp/Granite/application/platforms/application_sdl3.cpp:262
#16 0x000055555588722b in Vulkan::WSI::begin_frame (this=0x555556c051c0) at /tmp/Granite/vulkan/wsi.cpp:570
#17 0x000055555562f57b in Granite::Application::run_frame (this=0x555556c051b0) at /tmp/Granite/application/application.cpp:235
#18 0x000055555561989f in Granite::WSIPlatformSDL::thread_main (this=0x555556c0a5d0, app=0x555556c051b0, ctx=std::unique_ptr<Granite::Global::GlobalManagers> = {...})
    at /tmp/Granite/application/platforms/application_sdl3.cpp:613
#19 0x0000555555619598 in Granite::WSIPlatformSDL::run_loop (this=0x555556c0a5d0, app=0x555556c051b0) at /tmp/Granite/application/platforms/application_sdl3.cpp:561
#20 0x0000555555614dfc in Granite::application_main (query_application_interface=0x555556194d95 <Granite::query_application_interface(Granite::ApplicationQuery, void*, unsigned long)>, 
    create_application=0x555555607d69 <Granite::application_create(int, char**)>, argc=1, argv=0x7fffffffe178) at /tmp/Granite/application/platforms/application_sdl3.cpp:785
#21 0x000055555561460a in main (argc=1, argv=0x7fffffffe178) at /tmp/Granite/application/application_entry.cpp:93
```

**Comment by Themaister** [comment]
GPU is AMD RX 6800 running Mesa main.

**Comment by Kontrabant** [comment]
Can you update to the latest version and see if it still hangs? The version you are using is old enough that the last SDL function called before it gets stuck doesn’t exist anymore, nor do X11 functions block by default anymore.

**Comment by Themaister** [comment]
Thanks, it's fixed now on latest git. I'll update my submodule reference.

**Comment by Kontrabant** [comment]
To note, this hang was most likely caused by the lack of timer support being enabled (same as the related joystick issue), as the old X11 sync code blocked until it received exactly the sequence of events it expected, or timed out. The current X11 code potentially suffers from the same issue, except now it runs asynchronously and only does a blocking sync if manually requested, which is likely why it worked after updating.

It's fixed properly now that timer support isn't considered optional.
