### ISSUE TITLE
Segmentation fault in `SDL_BlitScaled` and `SDL_SoftStretch`

### ISSUE THREAD

**Issue by oddbookworm** [libsdl-org/SDL#8878]
Someone reported a segfault to us at `pygame-ce` when scaling a very large surface. I tracked it down to [this line](https://github.com/pygame-community/pygame-ce/blob/main/src_c/transform.c#L471) in our source code. As a test, I created a reproducer in pure C, and here is that reproducer
```C
#include <SDL2/SDL.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Surface *src = SDL_CreateRGBSurfaceWithFormat(0, 34688, 15507, 32, SDL_PIXELFORMAT_RGBA32);
    SDL_Surface *dst = SDL_CreateRGBSurfaceWithFormat(0, 12141, 5427, 32, SDL_PIXELFORMAT_RGBA32);

    SDL_LockSurface(src);

    SDL_SoftStretch(src, NULL, dst, NULL);

    SDL_UnlockSurface(src);

    return 0;
}
```

I tried not locking the surface and using `SDL_BlitScaled` in pygame-ce instead as the docs suggest, but that doesn't fix it. I get the same segfault ultimately tracing to [this line in SDL's video/SDL_stretch.c](https://github.com/libsdl-org/SDL/blob/SDL2/src/video/SDL_stretch.c#L920). That's the same line the reproducer segfaults at.

Notably, if I do the same switch in my reproducer, I get a different segfault, here's the gdb backtrace for that one
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e83f8b in SDL_Blit_Slow (info=<optimized out>) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_blit_slow.c:87
87                      DISEMBLE_RGBA(src, srcbpp, src_fmt, srcpixel, srcR, srcG, srcB, srcA);                                                                                                                                                                                       
(gdb) bt
#0  0x00007ffff7e83f8b in SDL_Blit_Slow (info=<optimized out>) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_blit_slow.c:87
#1  0x00007ffff7e60c92 in SDL_SoftBlit (src=0x5555555a21b0, srcrect=0x7fffffffd790, dst=0x5555555a0980, dstrect=0x7fffffffd780) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_blit.c:87
#2  0x00007ffff7e90804 in SDL_PrivateLowerBlitScaled (scaleMode=SDL_ScaleModeNearest, dstrect=0x7fffffffd780, dst=0x5555555a0980, srcrect=0x7fffffffd790, src=0x5555555a21b0) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_surface.c:829
#3  SDL_PrivateUpperBlitScaled (src=0x5555555a21b0, srcrect=<optimized out>, dst=0x5555555a0980, dstrect=0x0, scaleMode=SDL_ScaleModeNearest) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_surface.c:964
#4  0x00005555555551cd in main ()
```

**Comment by 1bsyl** [comment]
SDL3 testcase, 
seems, overflow issue, with nearest and linear scale mode: 

```

#include <SDL3/SDL.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Surface *src = SDL_CreateSurface(34688, 15507, SDL_PIXELFORMAT_RGBA32);
    SDL_Surface *dst = SDL_CreateSurface(12141, 5427, SDL_PIXELFORMAT_RGBA32);

    SDL_LockSurface(src);

    SDL_SoftStretch(src, NULL, dst, NULL, SDL_SCALEMODE_NEAREST);
    
    SDL_SoftStretch(src, NULL, dst, NULL, SDL_SCALEMODE_LINEAR);

    SDL_UnlockSurface(src);

    return 0;
}

```

nearest
```
src/video/SDL_stretch.c:902:5: runtime error: left shift of 34688 by 16 places cannot be represented in type 'int'
src/video/SDL_stretch.c:904:9: runtime error: signed integer overflow: 15479 * 138752 cannot be represented in type 'int'

```
linear
```
src/video/SDL_stretch.c:227:16: runtime error: signed integer overflow: 2147352109 + 187242 cannot be represented in type 'int'
src/video/SDL_stretch.c:439:22: runtime error: signed integer overflow: 2147352109 + 187242 cannot be represented in type 'int'


```


maybe this could be caught before, with https://github.com/libsdl-org/SDL/issues/8879

**Comment by slouken** [comment]
Great repro, thanks! This is fixed in SDL2 and SDL3.

**Comment by 1bsyl** [comment]
still seeing: 
```

src/video/SDL_stretch.c:228:16: runtime error: signed integer overflow: 2147352109 + 187242 cannot be represented in type 'int'
src/video/SDL_stretch.c:440:22: runtime error: signed integer overflow: 2147352109 + 187242 cannot be represented in type 'int'


```

**Comment by 1bsyl** [comment]
```
diff --git a/src/video/SDL_stretch.c b/src/video/SDL_stretch.c
index 2258746d9..263119e31 100644
--- a/src/video/SDL_stretch.c
+++ b/src/video/SDL_stretch.c
@@ -144,8 +144,10 @@ int SDL_SoftStretch(SDL_Surface *src, const SDL_Rect *srcrect,
 
 #define BILINEAR___START                                                              \
     int i;                                                                            \
-    int fp_sum_h, fp_step_h, left_pad_h, right_pad_h;                                 \
-    int fp_sum_w, fp_step_w, left_pad_w, right_pad_w;                                 \
+    Sint64 fp_sum_h;                                                                  \
+    int fp_step_h, left_pad_h, right_pad_h;                                           \
+    Sint64 fp_sum_w;                                                                  \
+    int fp_step_w, left_pad_w, right_pad_w;                                           \
     int fp_sum_w_init, left_pad_w_init, right_pad_w_init, dst_gap, middle_init;       \
     get_scaler_datas(src_h, dst_h, &fp_sum_h, &fp_step_h, &left_pad_h, &right_pad_h); \
     get_scaler_datas(src_w, dst_w, &fp_sum_w, &fp_step_w, &left_pad_w, &right_pad_w); \
@@ -194,7 +196,7 @@ static void get_scaler_datas(int src_nb, int dst_nb, int *fp_start, int *fp_step
 
     int step = FIXED_POINT(src_nb) / (dst_nb); /* source step in fixed point */
     int x0 = FP_ONE / 2;                       /* dst first pixel center at 0.5 in fixed point */
-    int fp_sum;
+    Sint64 fp_sum;
     int i;
 #if 0
     /* scale to source coordinates */

```

**Comment by slouken** [comment]
Sure, go ahead and commit that and cherry-pick -x to SDL2. Thanks!
