### ISSUE TITLE
Segfault in 2D Vulkan renderer

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9131]
Running `SDL_RENDER_DRIVER=vulkan testsprite --info render 10000`, we end up with `rendererData->currentPipelineState` being NULL on a vkCmdBindDescriptorSets call.

testsprite without command line arguments (rendering less sprites per frame) does _not_ crash.

```
INFO: Current renderer:
INFO:   Renderer vulkan:
INFO:     Flags: 0x00000002 (Accelerated)
INFO:     Texture formats (9): ARGB8888, XRGB8888, 0x16572004, 0x1a204008, YV12, IYUV, NV12, NV21, 0x30313050
INFO:     Max Texture Size: 16384x16384

Thread 1 "testsprite" received signal SIGSEGV, Segmentation fault.
VULKAN_SetDrawState (renderer=0x5555555ea920, cmd=0x5555559c58f0, shader=SHADER_RGB, shader_constants=0x7fffffffd740, topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, imageViewCount=1, 
    imageViews=0x555555949900, sampler=0x555555930430, matrix=0x0, stateCache=0x7fffffffd7e8) at /home/icculus/projects/SDL/src/render/vulkan/SDL_render_vulkan.c:3237
3237	        vkCmdBindDescriptorSets(rendererData->currentCommandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, rendererData->currentPipelineState->pipelineLayout,
(gdb) bt
#0  VULKAN_SetDrawState (renderer=0x5555555ea920, cmd=0x5555559c58f0, shader=SHADER_RGB, shader_constants=0x7fffffffd740, topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, 
    imageViewCount=1, imageViews=0x555555949900, sampler=0x555555930430, matrix=0x0, stateCache=0x7fffffffd7e8)
    at /home/icculus/projects/SDL/src/render/vulkan/SDL_render_vulkan.c:3237
#1  0x00007ffff7d7a4e8 in VULKAN_SetCopyState (renderer=0x5555555ea920, cmd=0x5555559c58f0, matrix=0x0, stateCache=0x7fffffffd7e8)
    at /home/icculus/projects/SDL/src/render/vulkan/SDL_render_vulkan.c:3338
#2  0x00007ffff7d7ab80 in VULKAN_RunCommandQueue (renderer=0x5555555ea920, cmd=0x5555559c58f0, vertices=0x7fffe3a0d010, vertsize=1959232)
    at /home/icculus/projects/SDL/src/render/vulkan/SDL_render_vulkan.c:3478
#3  0x00007ffff7d16e61 in FlushRenderCommands (renderer=0x5555555ea920) at /home/icculus/projects/SDL/src/render/SDL_render.c:289
#4  0x00007ffff7d2452b in SDL_RenderPresent_REAL (renderer=0x5555555ea920) at /home/icculus/projects/SDL/src/render/SDL_render.c:4399
#5  0x00007ffff7ce1b05 in SDL_RenderPresent (a=0x5555555ea920) at /home/icculus/projects/SDL/src/dynapi/SDL_dynapi_procs.h:570
#6  0x000055555555b12d in MoveSprites (renderer=0x5555555ea920, sprite=0x555555949810) at /home/icculus/projects/SDL/test/testsprite.c:386
#7  0x000055555555b229 in SDL_AppIterate () at /home/icculus/projects/SDL/test/testsprite.c:406
#8  0x00007ffff7d15ea6 in SDL_IterateMainCallbacks (pump_events=1) at /home/icculus/projects/SDL/src/main/SDL_main_callbacks.c:124
#9  0x00007ffff7f16cb5 in SDL_EnterAppMainCallbacks_REAL (argc=4, argv=0x7fffffffdd08, appinit=0x55555555b34f <SDL_AppInit>, appiter=0x55555555b16c <SDL_AppIterate>, 
    appevent=0x55555555b144 <SDL_AppEvent>, appquit=0x555555559a14 <SDL_AppQuit>) at /home/icculus/projects/SDL/src/main/generic/SDL_sysmain_callbacks.c:48
#10 0x00007ffff7ce59df in SDL_EnterAppMainCallbacks (a=4, b=0x7fffffffdd08, c=0x55555555b34f <SDL_AppInit>, d=0x55555555b16c <SDL_AppIterate>, e=0x55555555b144 <SDL_AppEvent>, 
    f=0x555555559a14 <SDL_AppQuit>) at /home/icculus/projects/SDL/src/dynapi/SDL_dynapi_procs.h:949
#11 0x00005555555599e3 in SDL_main (argc=4, argv=0x7fffffffdd08) at /home/icculus/projects/SDL/include/SDL3/SDL_main_impl.h:57
#12 0x00007ffff7cd13b4 in SDL_RunApp_REAL (argc=4, argv=0x7fffffffdd08, mainFunction=0x5555555599a3 <SDL_main>, reserved=0x0) at /home/icculus/projects/SDL/src/core/SDL_runapp.c:41
#13 0x00007ffff7cd73b0 in SDL_RunApp_DEFAULT (a=4, b=0x7fffffffdd08, c=0x5555555599a3 <SDL_main>, d=0x0) at /home/icculus/projects/SDL/src/dynapi/SDL_dynapi_procs.h:586
#14 0x00007ffff7ce1e09 in SDL_RunApp (a=4, b=0x7fffffffdd08, c=0x5555555599a3 <SDL_main>, d=0x0) at /home/icculus/projects/SDL/src/dynapi/SDL_dynapi_procs.h:586
#15 0x0000555555559a12 in main (argc=4, argv=0x7fffffffdd08) at /home/icculus/projects/SDL/include/SDL3/SDL_main_impl.h:201
(gdb) p rendererData->currentPipelineState 
$1 = (VULKAN_PipelineState *) 0x0
```

**Comment by ImJustAskingDude** [comment]
Saw the same behavior when simply trying to render 10000 rectangles with Vulkan renderer, and also does NOT crash when rendering 1000 rectangles

**Comment by slouken** [comment]
@danginsburg?
