### ISSUE TITLE
Emscripten: TypeError when switching renderer from opengles2 to software

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9880]
A TypeError is thrown when the renderer is switched in testcolorspace.

Console output:
```
testcolorspace.js:1487 INFO: There are 2 render drivers:
testcolorspace.js:1487 INFO:     opengles2
testcolorspace.js:1487 INFO:     software
testcolorspace.js:1487 INFO: Created renderer opengles2
testcolorspace.js:1487 INFO: HDR disabled
testcolorspace.js:1487 INFO: Created renderer software
testcolorspace.js:1487 INFO: HDR disabled
```

Backtrace:
```
testcolorspace.js:922 Uncaught TypeError: Cannot read properties of null (reading 'createImageData')
    at 167132 (testcolorspace.js:922:427)
    at runMainThreadEmAsm (testcolorspace.js:4117:35)
    at _emscripten_asm_const_int_sync_on_main_thread (testcolorspace.js:4119:86)
    at testcolorspace.wasm.Emscripten_UpdateWindowFramebuffer (SDL_emscriptenframebuffer.c:70:5)
    at testcolorspace.wasm.SDL_UpdateWindowSurfaceRects (SDL_video.c:3277:12)
    at testcolorspace.wasm.SDL_UpdateWindowSurface (SDL_video.c:3263:12)
    at testcolorspace.wasm.SW_RenderPresent (SDL_render_sw.c:1002:12)
    at testcolorspace.wasm.SDL_RenderPresent (SDL_render.c:4455:9)
    at testcolorspace.wasm.loop (testcolorspace.c:560:9)
    at callUserCallback (testcolorspace.js:4366:9)
```
I think it's failing [here](https://github.com/libsdl-org/SDL/blob/89a4d9ae67e82913af71a93611f396530a05f61d/src/video/emscripten/SDL_emscriptenframebuffer.c#L85)

**Comment by slouken** [comment]
We are scoping work for the SDL 3.2.0 release, so please let us know if this is a showstopper for you.

**Comment by madebr** [comment]
This is not a showstopper, I just want to make sure this will work within the current api.
When dropping a file in the browser, I think you need to act immediately and not wait until the event is delivered.
Common web javascript has no access to the file system.
